import type { PortfolioDocument } from '../../models/Portfolio';
import { getEnvironmentOpenOrders,getEnvironmentPosition } from '../delta';
import { readRuntimeActivity,readStatus } from '../state';
import { hasActivePortfolioTrades } from '../trades/repository';
import { findBlockingEntryIntent } from '../entry-intents/repository';
import { acquireLease,newLeaseOwner,portfolioEntryLeaseKey,releaseLease,verifyLeaseOwnership,type RuntimeLease } from '../runtime/leases';
export type DeletionDependencies={status:(id:string)=>any;activity:(id:string)=>any;hasActiveTrades:(id:string)=>Promise<boolean>;blockingIntent:(id:string)=>Promise<any>;position:(productId:number,environment:'real'|'demo')=>Promise<any>;openOrders:(productId:number,environment:'real'|'demo')=>Promise<any[]>};
const defaults:DeletionDependencies={status:readStatus,activity:readRuntimeActivity,hasActiveTrades:hasActivePortfolioTrades,blockingIntent:findBlockingEntryIntent,position:getEnvironmentPosition,openOrders:getEnvironmentOpenOrders};
export async function verifyPortfolioDeletion(portfolio:PortfolioDocument&{_id:NonNullable<PortfolioDocument['_id']>},dependencies:DeletionDependencies=defaults){const id=portfolio._id.toHexString(),status=dependencies.status(id),activity=dependencies.activity(id);if(status.running===true||activity.executionInProgress===true||Number(status.position?.size||0)!==0||status.activeTrade!=null||status.pending!=null||await dependencies.hasActiveTrades(id))return {ok:false as const,reason:'ACTIVE'};if(await dependencies.blockingIntent(id))return {ok:false as const,reason:'ENTRY_UNRESOLVED'};let position:any,orders:any[];try{[position,orders]=await Promise.all([dependencies.position(portfolio.productId,portfolio.environment),dependencies.openOrders(portfolio.productId,portfolio.environment)]);}catch{return {ok:false as const,reason:'VERIFICATION_FAILED'};}if(Number(position?.size||0)!==0||orders.length>0)return {ok:false as const,reason:'ACTIVE'};return {ok:true as const};}

export type CoordinatedDeletionDependencies={acquire:(key:string,owner:string,leaseMs:number)=>Promise<RuntimeLease|null>;owns:(lease:RuntimeLease)=>Promise<boolean>;release:(lease:RuntimeLease)=>Promise<unknown>;verify:(portfolio:PortfolioDocument&{_id:NonNullable<PortfolioDocument['_id']>})=>Promise<{ok:true}|{ok:false;reason:string}>;remove:(id:string)=>Promise<boolean>};
const coordinatedDefaults:CoordinatedDeletionDependencies={acquire:(key,owner,leaseMs)=>acquireLease(key,owner,leaseMs),owns:lease=>verifyLeaseOwnership(lease),release:lease=>releaseLease(lease),verify:portfolio=>verifyPortfolioDeletion(portfolio),remove:async()=>false};
export async function deletePortfolioCoordinated(portfolio:PortfolioDocument&{_id:NonNullable<PortfolioDocument['_id']>},remove:(id:string)=>Promise<boolean>,dependencies:Partial<CoordinatedDeletionDependencies>={}){const deps={...coordinatedDefaults,...dependencies,remove},id=portfolio._id.toHexString(),lease=await deps.acquire(portfolioEntryLeaseKey(id),newLeaseOwner('delete'),90_000);if(!lease)return {ok:false as const,reason:'IN_PROGRESS'};try{const verified=await deps.verify(portfolio);if(!verified.ok)return verified;if(!await deps.owns(lease))return {ok:false as const,reason:'IN_PROGRESS'};if(!await deps.remove(id))return {ok:false as const,reason:'NOT_FOUND'};return {ok:true as const};}finally{await deps.release(lease);}}
