import { getPublicProduct,getPublicTicker,type PortfolioEnvironment } from '../delta';
import { findPortfolio,insertPortfolio } from './repository';
import type { PortfolioDocument } from '../../models/Portfolio';
import { readStatus } from '../state';
export function normalizePortfolioSymbol(value:unknown){if(typeof value!=='string')throw new Error('SYMBOL_REQUIRED');const symbol=value.trim().toUpperCase();if(!symbol)throw new Error('SYMBOL_REQUIRED');if(symbol.length>30||!/^[A-Z0-9][A-Z0-9_-]*$/.test(symbol))throw new Error('SYMBOL_FORMAT');return symbol;}
export function normalizePortfolioEnvironment(value:unknown):PortfolioEnvironment{if(value==='real'||value==='demo')return value;throw new Error('ENVIRONMENT_REQUIRED');}
const finite=(value:unknown)=>{const number=Number(value);return value!=null&&value!==''&&Number.isFinite(number)?number:null;};const asset=(value:any)=>typeof value==='string'?value:typeof value?.symbol==='string'?value.symbol:null;
export type PortfolioDependencies={find:typeof findPortfolio;insert:typeof insertPortfolio;product:typeof getPublicProduct;now:()=>Date};
const defaults:PortfolioDependencies={find:findPortfolio,insert:insertPortfolio,product:getPublicProduct,now:()=>new Date()};
export async function createPortfolio(rawSymbol:unknown,rawEnvironment:unknown,dependencies:PortfolioDependencies=defaults){const symbol=normalizePortfolioSymbol(rawSymbol),environment=normalizePortfolioEnvironment(rawEnvironment);if(await dependencies.find(environment,symbol))throw new Error('PORTFOLIO_EXISTS');let product:any;try{product=await dependencies.product(symbol,environment);}catch(error:any){const message=String(error?.message||error);if(/not[_ ]?found|invalid[_ ]?product|404/i.test(message))throw new Error('SYMBOL_NOT_FOUND');throw new Error('DELTA_VERIFICATION_FAILED');}const productId=Number(product?.id);if(!product||!Number.isSafeInteger(productId)||productId<=0||String(product.symbol||'').toUpperCase()!==symbol)throw new Error('SYMBOL_NOT_FOUND');const now=dependencies.now(),document:Omit<PortfolioDocument,'_id'>={symbol,productId,name:typeof product.description==='string'?product.description:typeof product.name==='string'?product.name:null,contractValue:finite(product.contract_value),settlingAsset:asset(product.settling_asset),underlyingAsset:asset(product.underlying_asset),environment,createdAt:now,updatedAt:now};try{return await dependencies.insert(document);}catch(error:any){if(error?.code===11000)throw new Error('PORTFOLIO_EXISTS');throw new Error('PORTFOLIO_SAVE_FAILED');}}
export function sanitizePortfolio(row:PortfolioDocument){return {id:row._id?.toHexString(),symbol:row.symbol,productId:row.productId,name:row.name,contractValue:row.contractValue,settlingAsset:row.settlingAsset,underlyingAsset:row.underlyingAsset,environment:row.environment,createdAt:row.createdAt,updatedAt:row.updatedAt};}
export function portfolioDeletionUiState(row:PortfolioDocument,status:any=readStatus(row._id?.toHexString())){const raw=status.position?.size,positionSize=finite(raw),known=positionSize!==null;if(!known)return {allowed:false,positionKnown:false,positionSize:null,reason:'Position status unavailable. Deletion is disabled.'};if(positionSize!==0)return {allowed:false,positionKnown:true,positionSize,reason:'Close the active position before deleting this portfolio.'};if(status.running===true||status.activeTrade!=null||status.pending!=null)return {allowed:false,positionKnown:true,positionSize,reason:'Stop trading activity before deleting this portfolio.'};return {allowed:true,positionKnown:true,positionSize,reason:null};}
export async function portfolioWithPrices(rows:PortfolioDocument[]){const results=await Promise.allSettled(rows.map(row=>getPublicTicker(row.symbol,row.environment)));return rows.map((row,index)=>{const result=results[index];const price=result.status==='fulfilled'?finite(result.value?.close):null;return {...sanitizePortfolio(row),currentPrice:price,deletion:portfolioDeletionUiState(row)};});}
