import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { claimTradeFills,FillOwnershipConflictError,type FillClaimStore,type FillIdentity } from '../lib/trades/fill-claims';
import { persistClosedTrade } from '../lib/trades/persistence';
import type { TradeFillClaimDocument,TradeFillRole } from '../models/TradeFillClaim';

class MemoryClaims implements FillClaimStore {
  rows=new Map<string,TradeFillClaimDocument>();
  key(identity:FillIdentity){return `${identity.environment}:${identity.productId}:${identity.fillId}`;}
  async insertOne(document:TradeFillClaimDocument){const key=this.key(document);if(this.rows.has(key)){const error:any=new Error('duplicate key');error.code=11000;throw error;}this.rows.set(key,{...document});}
  async findOne(identity:FillIdentity){return this.rows.get(this.key(identity))??null;}
}

const dependencies=(store:MemoryClaims,historicalOwners:()=>Promise<string[]>=async()=>[])=>({store,historicalOwners,now:()=>new Date('2026-09-02T00:00:00.000Z')});
const claim=(store:MemoryClaims,tradeId:string,fillIds=['F123'],role:TradeFillRole='ENTRY',environment:'real'|'demo'='demo',portfolioId=`portfolio-${tradeId}`)=>claimTradeFills({environment,productId:7,portfolioId,tradeId,fillIds,role},dependencies(store));

test('first fill claim succeeds',async()=>{const store=new MemoryClaims();assert.equal((await claim(store,'trade-a'))[0].status,'CLAIMED');assert.equal(store.rows.size,1);});
test('same trade reclaim is idempotent',async()=>{const store=new MemoryClaims();await claim(store,'trade-a');assert.equal((await claim(store,'trade-a'))[0].status,'ALREADY_OWNED');assert.equal(store.rows.size,1);});
test('different trade claim raises ownership conflict',async()=>{const store=new MemoryClaims();await claim(store,'trade-a');await assert.rejects(()=>claim(store,'trade-b'),(error:any)=>error instanceof FillOwnershipConflictError&&error.code==='FILL_OWNERSHIP_CONFLICT');});
test('true concurrent different-trade claim produces exactly one owner',async()=>{const store=new MemoryClaims();const results=await Promise.allSettled([claim(store,'trade-a'),claim(store,'trade-b')]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal(results.filter(result=>result.status==='rejected').length,1);assert.equal(store.rows.size,1);});
test('concurrent same-trade claims are idempotent with one durable owner',async()=>{const store=new MemoryClaims();const results=await Promise.all([claim(store,'trade-a'),claim(store,'trade-a')]);assert.equal(results.flat().filter(result=>result.status==='CLAIMED').length,1);assert.equal(store.rows.size,1);});
test('bot-owned fill cannot be reclaimed by manual lifecycle',async()=>{const store=new MemoryClaims();await claim(store,'bot-trade');await assert.rejects(()=>claim(store,'manual-trade'),/FILL_OWNERSHIP_CONFLICT/);});
test('manual-owned fill cannot be reclaimed by bot lifecycle',async()=>{const store=new MemoryClaims();await claim(store,'manual-trade');await assert.rejects(()=>claim(store,'bot-trade'),/FILL_OWNERSHIP_CONFLICT/);});
test('entry fill identity cannot enter two lifecycles',async()=>{const store=new MemoryClaims();await claim(store,'trade-a',['entry-fill'],'ENTRY');await assert.rejects(()=>claim(store,'trade-b',['entry-fill'],'ENTRY'),/FILL_OWNERSHIP_CONFLICT/);});
test('exit fill identity cannot close two lifecycles',async()=>{const store=new MemoryClaims();await claim(store,'trade-a',['exit-fill'],'EXIT');await assert.rejects(()=>claim(store,'trade-b',['exit-fill'],'EXIT'),/FILL_OWNERSHIP_CONFLICT/);});
test('multiple partial fills remain individually owned by one trade',async()=>{const store=new MemoryClaims();const result=await claim(store,'trade-a',['F1','F2','F3']);assert.deepEqual(result.map(row=>row.fillId),['F1','F2','F3']);assert.equal(store.rows.size,3);assert.equal([...store.rows.values()].every(row=>row.tradeId==='trade-a'),true);});
test('restart reclaim by same trade remains safe',async()=>{const store=new MemoryClaims();await claim(store,'trade-a');const restarted=await claim(store,'trade-a');assert.equal(restarted[0].status,'ALREADY_OWNED');});
test('claim survives trade update failure and permits only same-trade recovery',async()=>{const store=new MemoryClaims();await claim(store,'trade-a');const simulatedTradeWrite=async()=>{throw new Error('trade update failed');};await assert.rejects(simulatedTradeWrite,/trade update failed/);assert.equal((await claim(store,'trade-a'))[0].status,'ALREADY_OWNED');await assert.rejects(()=>claim(store,'trade-b'),/FILL_OWNERSHIP_CONFLICT/);});
test('concurrent manual reconstruction assigns a fill to only one lifecycle',async()=>{const store=new MemoryClaims();const results=await Promise.allSettled([claim(store,'manual-a',['manual-fill']),claim(store,'manual-b',['manual-fill'])]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal(store.rows.size,1);});

const fill=(id:string,orderId:string,side:'buy'|'sell',price:number,commission='0.1')=>({id,order_id:orderId,product_id:7,side,size:'1',price:String(price),commission,created_at:'2026-09-02T00:00:01.000Z'});
test('reused exit fill cannot double-count PnL or commission',async()=>{const store=new MemoryClaims(),entryA=fill('entry-a','order-a','buy',100),entryB=fill('entry-b','order-b','buy',100),exit=fill('shared-exit','exit-order','sell',110,'0.25'),records:any[]=[];const deps:any={upsert:async(document:any)=>{records.push(document);return document;},fills:async()=>({result:records.length?[entryB,exit]:[entryA,exit],complete:true}),orders:async()=>({result:[{id:'order-a',product_id:7},{id:'order-b',product_id:7},{id:'exit-order',product_id:7,reduce_only:true}],complete:true}),now:()=>new Date('2026-09-02T00:00:02.000Z').valueOf(),claimFills:(input:any)=>claimTradeFills(input,dependencies(store))};const base={direction:'long',source:'bot' as const,attributionStatus:'BOT_CONFIRMED',contracts:1,ownedContracts:1,contractValue:1,openedAt:new Date('2026-09-02T00:00:00.000Z').valueOf(),closedAtBoundary:new Date('2026-09-02T00:00:03.000Z').valueOf()};await persistClosedTrade({...base,tradeId:'trade-a',orderId:'order-a'},7,'XAUTUSD',null,deps,{portfolioId:'portfolio-a',environment:'demo'});await assert.rejects(()=>persistClosedTrade({...base,tradeId:'trade-b',orderId:'order-b'},7,'XAUTUSD',null,deps,{portfolioId:'portfolio-b',environment:'demo'}),/FILL_OWNERSHIP_CONFLICT/);assert.equal(records.length,1);assert.equal(records[0].grossPnL,10);assert.equal(records[0].brokerage,0.35);});
test('historical duplicate ownership is detected without selecting a winner',async()=>{const store=new MemoryClaims();await assert.rejects(()=>claimTradeFills({environment:'demo',productId:7,portfolioId:'portfolio-c',tradeId:'trade-c',fillIds:['legacy-fill'],role:'ENTRY'},dependencies(store,async()=>['legacy-a','legacy-b'])),(error:any)=>error instanceof FillOwnershipConflictError&&error.existingTradeIds.length===2);assert.equal(store.rows.size,0);});
test('real and demo use separate fill identities while same-environment portfolios conflict',async()=>{const store=new MemoryClaims();await claim(store,'demo-a',['F123'],'ENTRY','demo','portfolio-a');await claim(store,'real-a',['F123'],'ENTRY','real','portfolio-a');await assert.rejects(()=>claim(store,'demo-b',['F123'],'ENTRY','demo','portfolio-b'),/FILL_OWNERSHIP_CONFLICT/);assert.equal(store.rows.size,2);});
test('production claim ledger declares a database-enforced unique identity index',()=>{const source=fs.readFileSync(new URL('../lib/trades/fill-claims.ts',import.meta.url),'utf8');assert.match(source,/createIndex\(\{environment:1,productId:1,fillId:1\},\{unique:true,name:'exchange_fill_identity_unique'\}\)/);});
