import assert from 'node:assert/strict';
import test from 'node:test';
import { finalPreOrderSafetyCheck,type FinalPreOrderDependencies } from '../lib/runtime/final-preorder';
import { EntryNotTransmittedError,submitPreparedEntryIntent } from '../lib/entry-intents/service';

const setup={direction:'long' as const,trigger:100,sl:90,candleTime:1_000,configRevision:'rev'};
const config={revision:'rev',autoTrade:true,entryValidCandles:2,resolutionSec:60,riskPct:1,rr:8,minStopPct:0,maxEffectiveLeverage:100,maxFeeRiskPct:20,gstPct:18};
const input={identity:{portfolioId:'p1',environment:'demo' as const,symbol:'BTCUSD',productId:27},setup,config,product:{id:27,contractValue:0.01,tickSize:0.5,takerRate:0.0005}};
function harness(overrides:Partial<FinalPreOrderDependencies>={}){let positionCalls=0,marginCalls=0;const deps:FinalPreOrderDependencies={robotRunning:()=>true,refreshConfig:async()=>config,currentPending:()=>setup,latestCompletedCandleTime:()=>1_119,leaseOwned:async()=>true,leaseLost:()=>false,portfolioEntryAllowed:async()=>true,portfolio:async()=>({id:'p1',environment:'demo',symbol:'BTCUSD',productId:27}),position:async()=>{positionCalls++;return{size:0}},availableMargin:async()=>{marginCalls++;return 1_000},...overrides};return{deps,positionCalls:()=>positionCalls,marginCalls:()=>marginCalls};}
async function failureReason(value:ReturnType<typeof finalPreOrderSafetyCheck>){const result=await value;return result.ok?null:result.reason;}

test('final barrier uses fresh position/margin and unchanged risk formula',async()=>{const h=harness(),result=await finalPreOrderSafetyCheck(input,h.deps);assert.equal(result.ok,true);if(!result.ok)return;assert.equal(h.positionCalls(),1);assert.equal(h.marginCalls(),1);assert.equal(result.riskAmount,10);assert.equal(result.contracts,100);assert.equal(result.effectiveLeverage,0.1);});
test('changed final margin recalculates risk, contracts, leverage and fees',async()=>{const result=await finalPreOrderSafetyCheck(input,harness({availableMargin:async()=>500}).deps);assert.equal(result.ok,true);if(!result.ok)return;assert.equal(result.riskAmount,5);assert.equal(result.contracts,50);assert.ok(Number.isFinite(result.feeRiskPct));});
for(const [name,override,reason] of [
  ['Robot Stop',{robotRunning:()=>false},'FINAL_PREORDER_ROBOT_STOPPED'],
  ['AUTO_TRADE OFF',{refreshConfig:async()=>({...config,autoTrade:false})},'FINAL_PREORDER_AUTO_TRADE_OFF'],
  ['config change',{refreshConfig:async()=>({...config,revision:'new'})},'FINAL_PREORDER_CONFIG_CHANGED'],
  ['pending replacement',{currentPending:()=>({...setup,trigger:101})},'FINAL_PREORDER_PENDING_REPLACED'],
  ['expiry',{latestCompletedCandleTime:()=>1_120},'FINAL_PREORDER_PENDING_EXPIRED'],
  ['missing lease',{leaseOwned:async()=>false},'FINAL_PREORDER_LEASE_LOST'],
  ['heartbeat lease loss',{leaseLost:()=>true},'FINAL_PREORDER_LEASE_LOST'],
  ['portfolio deletion coordination',{portfolioEntryAllowed:async()=>false},'FINAL_PREORDER_DELETION_IN_PROGRESS'],
  ['fresh manual position',{position:async()=>({size:1})},'FINAL_PREORDER_POSITION_NONZERO'],
  ['invalid margin',{availableMargin:async()=>0},'FINAL_PREORDER_MARGIN_INVALID'],
  ['portfolio id mismatch',{portfolio:async()=>({id:'p2',environment:'demo',symbol:'BTCUSD',productId:27})},'FINAL_PREORDER_PORTFOLIO_MISMATCH'],
  ['product mismatch',{portfolio:async()=>({id:'p1',environment:'demo',symbol:'BTCUSD',productId:28})},'FINAL_PREORDER_PORTFOLIO_MISMATCH'],
  ['environment mismatch',{portfolio:async()=>({id:'p1',environment:'real',symbol:'BTCUSD',productId:27})},'FINAL_PREORDER_PORTFOLIO_MISMATCH']
] as const)test(`${name} blocks before submission`,async()=>assert.deepEqual(await failureReason(finalPreOrderSafetyCheck(input,harness(override as any).deps)),reason));
test('Candle1 and last valid instant pass; established post-window boundary expires',async()=>{assert.equal((await finalPreOrderSafetyCheck(input,harness({latestCompletedCandleTime:()=>1_060}).deps)).ok,true);assert.equal((await finalPreOrderSafetyCheck(input,harness({latestCompletedCandleTime:()=>1_119}).deps)).ok,true);assert.equal((await finalPreOrderSafetyCheck(input,harness({latestCompletedCandleTime:()=>1_120}).deps)).ok,false);});
test('quantity-dependent leverage, fee, and changed-quantity guards rerun',async()=>{assert.equal(await failureReason(finalPreOrderSafetyCheck({...input,config:{...config,maxEffectiveLeverage:0.01}},harness({refreshConfig:async()=>({...config,maxEffectiveLeverage:0.01})}).deps)),'FINAL_PREORDER_RISK_GUARD');assert.equal(await failureReason(finalPreOrderSafetyCheck({...input,config:{...config,maxFeeRiskPct:0}},harness({refreshConfig:async()=>({...config,maxFeeRiskPct:0})}).deps)),'FINAL_PREORDER_RISK_GUARD');assert.equal(await failureReason(finalPreOrderSafetyCheck({...input,expectedContracts:99},harness().deps)),'FINAL_PREORDER_RISK_GUARD');});
test('REAL and DEMO identity cannot cross',async()=>{const real={...input,identity:{...input.identity,environment:'real' as const}};assert.equal(await failureReason(finalPreOrderSafetyCheck(real,harness().deps)),'FINAL_PREORDER_PORTFOLIO_MISMATCH');});
test('known pre-transmission rejection is reset rather than marked ambiguous',async()=>{let barrierCalls=0,state='PREPARED';const intent:any={intentId:'i',clientOrderId:'c',portfolioId:'p1',productId:27};const dependencies:any={prepare:async()=>({...intent,state}),claim:async()=>{state='SUBMITTING';return{...intent,state}},reset:async()=>{state='PREPARED'},ambiguous:async()=>{state='AMBIGUOUS'},confirmed:async()=>null,touch:async()=>{},unresolved:async()=>[],lookup:async()=>null};const result=await submitPreparedEntryIntent(intent,async()=>{barrierCalls++;throw new EntryNotTransmittedError('FINAL_PREORDER_ROBOT_STOPPED')},dependencies);assert.equal(result.status,'REJECTED');assert.equal(state,'PREPARED');assert.equal(barrierCalls,1);});
test('failed barriers make zero market calls and a successful barrier permits exactly one',async()=>{let market=0;for(const deps of [harness({robotRunning:()=>false}).deps,harness({position:async()=>({size:1})}).deps]){const checked=await finalPreOrderSafetyCheck(input,deps);if(checked.ok)market++;}assert.equal(market,0);const checked=await finalPreOrderSafetyCheck(input,harness().deps);if(checked.ok)market++;assert.equal(market,1);});
test('second same-environment portfolio sizes from margin reduced by the first entry',async()=>{let available=1_000;const btc=await finalPreOrderSafetyCheck(input,harness({availableMargin:async()=>available}).deps);assert.equal(btc.ok,true);available=600;const xaut=await finalPreOrderSafetyCheck({...input,identity:{...input.identity,portfolioId:'p2',symbol:'XAUTUSD',productId:84},product:{...input.product,id:84}},harness({portfolio:async()=>({id:'p2',environment:'demo',symbol:'XAUTUSD',productId:84}),availableMargin:async()=>available}).deps);assert.equal(xaut.ok,true);if(btc.ok&&xaut.ok){assert.equal(btc.riskAmount,10);assert.equal(xaut.riskAmount,6);assert.ok(xaut.contracts<btc.contracts);}});
