import assert from 'node:assert/strict';
import test from 'node:test';
import { ObjectId } from 'mongodb';
import type { TradeDocument } from '../models/Trade';
import { backfillClosedManualFinancials, isEligibleStaleClosedManualTrade } from '../lib/trades/manual-financial-backfill';

const trade=(overrides:Partial<TradeDocument>={}):TradeDocument=>({_id:new ObjectId(),tradeId:'manual-stale',symbol:'XAUTUSD',productId:1,side:'SHORT',source:'exchange_existing',attributionStatus:'MANUAL_CONFIRMED',status:'CLOSED',entryTime:new Date(1),intendedEntryPrice:null,actualEntryPrice:4452.8,quantity:0.006,contracts:6,contractValue:0.001,initialSL:null,takeProfit:null,exitTime:new Date(2),intendedExitPrice:null,actualExitPrice:4452.82,exitReason:'MANUAL_CLOSE',grossPnL:-0.00012,brokerage:0.00630519,GST:null,otherCharges:null,totalCharges:null,netPnL:null,estimatedBrokerage:null,estimatedGST:null,estimatedTotalCharges:null,estimatedNetPnL:null,realizedR:null,entryOrderId:'entry',exitOrderId:'exit',entryClientOrderId:null,exitClientOrderId:null,entryFillIds:['entry-fill'],exitFillIds:['exit-fill'],financialStatus:'partial',feeDataSource:'delta_fills_commission',priceDataSource:'delta_weighted_fills',attributionNote:null,reconciliationError:null,createdAt:new Date(1),updatedAt:new Date(2),reconciledAt:new Date(2),...overrides});

function memoryCollection(initial:TradeDocument[]){
  const documents=initial.map(row=>({...row}));let writes=0,inserts=0;
  return {documents,get writes(){return writes;},get inserts(){return inserts;},collection:{find:()=>({toArray:async()=>documents}),updateOne:async(filter:any,update:any,options:any)=>{assert.equal(options.upsert,false);const index=documents.findIndex(row=>String(row._id)===String(filter._id)&&isEligibleStaleClosedManualTrade(row));if(index<0)return {modifiedCount:0};documents[index]={...documents[index],...update.$set};writes++;return {modifiedCount:1};},insertOne:async()=>{inserts++;}} as any};
}

test('eligible stale CLOSED MANUAL financials backfill once without changing identity or lifecycle data',async()=>{const original=trade(),id=String(original._id),entryIds=[...original.entryFillIds],exitIds=[...original.exitFillIds],memory=memoryCollection([original]);const dryRun=await backfillClosedManualFinancials(memory.collection,false);assert.equal(dryRun.eligibleCount,1);assert.equal(dryRun.modifiedCount,0);assert.equal(memory.writes,0);const first=await backfillClosedManualFinancials(memory.collection,true),saved=memory.documents[0];assert.equal(first.modifiedCount,1);assert.equal(String(saved._id),id);assert.equal(saved.tradeId,original.tradeId);assert.deepEqual(saved.entryFillIds,entryIds);assert.deepEqual(saved.exitFillIds,exitIds);assert.equal(saved.brokerage,0.00630519);assert.equal(saved.GST,null);assert.equal(saved.totalCharges,0.00630519);assert.ok(Math.abs((saved.netPnL??0)-(-0.00642519))<1e-12);assert.equal(saved.realizedR,null);assert.equal(saved.financialStatus,'actual');assert.equal(saved.status,'CLOSED');const second=await backfillClosedManualFinancials(memory.collection,true);assert.equal(second.eligibleCount,0);assert.equal(second.modifiedCount,0);assert.equal(memory.writes,1);assert.equal(memory.inserts,0);});

test('proven existing additional fee is included without adding GST again',async()=>{const memory=memoryCollection([trade({otherCharges:0.4})]);await backfillClosedManualFinancials(memory.collection,true);assert.equal(memory.documents[0].GST,null);assert.ok(Math.abs((memory.documents[0].totalCharges??0)-0.40630519)<1e-12);assert.ok(Math.abs((memory.documents[0].netPnL??0)-(-0.40642519))<1e-12);});

test('BOT, OPEN, RECONCILING, and already-actual manual records are untouched',async()=>{const records=[trade({_id:new ObjectId(),tradeId:'bot',source:'bot',attributionStatus:'BOT_CONFIRMED'}),trade({_id:new ObjectId(),tradeId:'open',status:'OPEN'}),trade({_id:new ObjectId(),tradeId:'reconciling',status:'RECONCILING'}),trade({_id:new ObjectId(),tradeId:'actual',totalCharges:0.1,netPnL:-0.2,financialStatus:'actual'})],memory=memoryCollection(records);const result=await backfillClosedManualFinancials(memory.collection,true);assert.equal(result.eligibleCount,0);assert.equal(result.modifiedCount,0);assert.equal(memory.writes,0);assert.equal(memory.inserts,0);assert.deepEqual(memory.documents,records);});
