import assert from 'node:assert/strict';
import test from 'node:test';
import { EventEmitter } from 'node:events';
import { ObjectId } from 'mongodb';
import type { ChildProcess } from 'node:child_process';
import { TradingRuntimeManager } from '../lib/runtime/manager';
import { getDeltaEnvironment } from '../lib/config';
import { persistOpenBotTrade } from '../lib/trades/persistence';

function portfolio(symbol:string,environment:'real'|'demo'){return {_id:new ObjectId(),symbol,environment,productId:Math.floor(Math.random()*100000)+1,name:null,contractValue:1,settlingAsset:'USD',underlyingAsset:symbol.replace('USD',''),createdAt:new Date(),updatedAt:new Date()};}
function fakeProcess(){const process=new EventEmitter() as ChildProcess&{killedByTest:boolean};process.killedByTest=false;process.kill=(()=>{process.killedByTest=true;process.emit('exit',0);return true;}) as any;return process;}
function testLeaseProvider(){return {acquire:async(portfolioId:string,ownerId:string)=>({key:`portfolio-runtime:${portfolioId}`,ownerId,acquiredAt:new Date(),expiresAt:new Date(Date.now()+30_000)}),release:async()=>true};}

test('runtime manager creates isolated simultaneous REAL and DEMO process boundaries',async()=>{const btcReal=portfolio('BTCUSD','real'),xautReal=portfolio('XAUTUSD','real'),btcDemo=portfolio('BTCUSD','demo'),rows=[btcReal,xautReal,btcDemo];const spawned=new Map<string,ReturnType<typeof fakeProcess>>();const manager=new TradingRuntimeManager(async()=>rows,row=>{const child=fakeProcess();spawned.set(row._id.toHexString(),child);return child;},testLeaseProvider());await manager.synchronize();assert.equal(manager.instances.size,3);assert.notEqual(manager.instances.get(btcReal._id.toHexString())?.process,manager.instances.get(xautReal._id.toHexString())?.process);assert.equal(manager.instances.get(btcReal._id.toHexString())?.portfolio.environment,'real');assert.equal(manager.instances.get(btcDemo._id.toHexString())?.portfolio.environment,'demo');});

test('removing or stopping one runtime does not alter other portfolio runtimes',async()=>{const btc=portfolio('BTCUSD','real'),xaut=portfolio('XAUTUSD','real');let rows=[btc,xaut];const spawned=new Map<string,ReturnType<typeof fakeProcess>>();const manager=new TradingRuntimeManager(async()=>rows,row=>{const child=fakeProcess();spawned.set(row._id.toHexString(),child);return child;},testLeaseProvider());await manager.synchronize();rows=[xaut];await manager.synchronize();assert.equal(spawned.get(btc._id.toHexString())?.killedByTest,true);assert.equal(spawned.get(xaut._id.toHexString())?.killedByTest,false);assert.equal(manager.instances.size,1);assert.ok(manager.instances.has(xaut._id.toHexString()));});

test('two manager instances cannot spawn the same portfolio while its process lease is held',async()=>{const row=portfolio('BTCUSD','demo'),held=new Map<string,string>(),leases={acquire:async(id:string,ownerId:string)=>{if(held.has(id))return null;held.set(id,ownerId);return{key:`portfolio-runtime:${id}`,ownerId,acquiredAt:new Date(),expiresAt:new Date(Date.now()+30_000)};},release:async(lease:any)=>{held.delete(lease.key.replace('portfolio-runtime:',''));return true;}};let spawns=0;const spawn=()=>{spawns++;return fakeProcess();},first=new TradingRuntimeManager(async()=>[row],spawn,leases),second=new TradingRuntimeManager(async()=>[row],spawn,leases);await Promise.all([first.synchronize(),second.synchronize()]);assert.equal(spawns,1);assert.equal(first.instances.size+second.instances.size,1);});

test('REAL and DEMO resolve separate URLs and credential labels without fallback',()=>{const real=getDeltaEnvironment('real'),demo=getDeltaEnvironment('demo');assert.equal(real.baseUrl,'https://api.india.delta.exchange');assert.equal(demo.baseUrl,'https://cdn-ind.testnet.deltaex.org');assert.deepEqual(real.credentialLabels,['DELTA_LIVE_API_KEY','DELTA_LIVE_API_SECRET']);assert.deepEqual(demo.credentialLabels,['DELTA_DEMO_API_KEY','DELTA_DEMO_API_SECRET']);assert.notEqual(real.credentialLabels[0],demo.credentialLabels[0]);});

test('worker keeps per-runtime control, pending, active trade, logs, events, and loss state inside child process memory',()=>{const source=require('node:fs').readFileSync(require('node:path').join(process.cwd(),'worker.ts'),'utf8');assert.match(source,/PORTFOLIO_RUNTIME_ID/);assert.match(source,/TradingRuntimeManager/);for(const state of ['pending','activeTrade','uiLogs','tradeEvents','lossStreak'])assert.match(source,new RegExp(`let ${state}`));assert.match(source,/readControl\(portfolioId\)/);assert.match(source,/writeStatus\([\s\S]*portfolioId\)/);});

test('new trade persistence stores portfolio and environment and namespaces exchange identity',async()=>{let saved:any;const dependencies:any={upsert:async(document:any)=>{saved=document;return document;},fills:async()=>({result:[],complete:true}),orders:async()=>({result:[],complete:true}),now:()=>Date.now()};const portfolioId=new ObjectId().toHexString();await persistOpenBotTrade({direction:'long',orderId:'same-order',contracts:1,contractValue:0.001},27,'BTCUSD',dependencies,{portfolioId,environment:'demo'});assert.equal(saved.portfolioId,portfolioId);assert.equal(saved.environment,'demo');assert.match(saved.tradeId,new RegExp(`^demo:${portfolioId}:`));});
