import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { ObjectId } from 'mongodb';
import { NextRequest } from 'next/server';
import { createPortfolio,normalizePortfolioEnvironment,normalizePortfolioSymbol,sanitizePortfolio,type PortfolioDependencies } from '../lib/portfolio/service';
import { DELETE,GET,POST } from '../app/api/portfolio/route';

test('portfolio APIs require authentication before portfolio or Delta access',async()=>{assert.equal((await GET(new NextRequest('http://localhost/api/portfolio'))).status,401);assert.equal((await POST(new NextRequest('http://localhost/api/portfolio',{method:'POST',headers:{origin:'http://localhost','content-type':'application/json'},body:JSON.stringify({symbol:'XAUTUSD',environment:'demo'})}))).status,401);assert.equal((await DELETE(new NextRequest('http://localhost/api/portfolio',{method:'DELETE'}))).status,401);});

test('portfolio symbols normalize whitespace and case and reject unsafe input',()=>{assert.equal(normalizePortfolioSymbol('  xautusd  '),'XAUTUSD');assert.throws(()=>normalizePortfolioSymbol('   '),/SYMBOL_REQUIRED/);for(const value of ['BTC/USD','BTC USD','BTC$USD','A'.repeat(31)])assert.throws(()=>normalizePortfolioSymbol(value),/SYMBOL_FORMAT/);});
test('portfolio environment accepts only the stable real and demo enum',()=>{assert.equal(normalizePortfolioEnvironment('real'),'real');assert.equal(normalizePortfolioEnvironment('demo'),'demo');for(const value of ['live','production','testnet','REAL',undefined])assert.throws(()=>normalizePortfolioEnvironment(value),/ENVIRONMENT_REQUIRED/);});

function memoryPortfolio(product:(symbol:string,environment:'real'|'demo')=>Promise<any>){const documents:any[]=[];let productCalls=0;const dependencies:PortfolioDependencies={find:async(environment,symbol)=>documents.find(row=>row.environment===environment&&row.symbol===symbol)??null,insert:async(document:any)=>{if(documents.some(row=>row.environment===document.environment&&row.symbol===document.symbol)){const error:any=new Error('duplicate');error.code=11000;throw error;}const saved={...document,_id:new ObjectId()};documents.push(saved);return saved;},product:async(symbol,environment)=>{productCalls++;return product(symbol,environment);},now:()=>new Date('2026-09-01T00:00:00.000Z')};return {documents,dependencies,get productCalls(){return productCalls;}};}

test('valid Delta product creates one normalized stable portfolio in the selected environment',async()=>{let selected='';const memory=memoryPortfolio(async(symbol,environment)=>{selected=environment;return{id:181689,symbol,description:'Gold Futures',contract_value:'0.001',settling_asset:{symbol:'USD'},underlying_asset:{symbol:'XAUT'}};});const saved=await createPortfolio(' xautusd ','demo',memory.dependencies);assert.equal(saved.symbol,'XAUTUSD');assert.equal(saved.environment,'demo');assert.equal(selected,'demo');assert.equal(saved.productId,181689);assert.equal(saved.contractValue,0.001);assert.equal(memory.documents.length,1);await assert.rejects(()=>createPortfolio('XAUTUSD','demo',memory.dependencies),/PORTFOLIO_EXISTS/);assert.equal(memory.documents.length,1);assert.equal(memory.productCalls,1);});

test('nonexistent or unverifiable Delta products never create portfolio records',async()=>{for(const product of [async()=>{throw new Error('product_not_found');},async()=>{throw new Error('DELTA_NETWORK_TIMEOUT');},async()=>({id:2,symbol:'OTHER'})]){const memory=memoryPortfolio(product);await assert.rejects(()=>createPortfolio('BTCUSDD','real',memory.dependencies),/SYMBOL_NOT_FOUND|DELTA_VERIFICATION_FAILED/);assert.equal(memory.documents.length,0);}});

test('portfolio response is sanitized and UI provides environments, prices, refresh, deletion, and runtime routing',()=>{const row:any={_id:new ObjectId(),symbol:'XAUTUSD',productId:181689,name:'Gold',contractValue:0.001,settlingAsset:'USD',underlyingAsset:'XAUT',environment:'demo',createdAt:new Date(),updatedAt:new Date(),secret:'never'};const output:any=sanitizePortfolio(row);assert.equal(output.secret,undefined);assert.equal(JSON.stringify(output).includes('never'),false);const ui=fs.readFileSync(path.join(process.cwd(),'components/PortfolioManager.tsx'),'utf8'),worker=fs.readFileSync(path.join(process.cwd(),'worker.ts'),'utf8'),delta=fs.readFileSync(path.join(process.cwd(),'lib/delta.ts'),'utf8');for(const expected of ['Add Portfolio','Trading Environment','Current Price','DELETE','setInterval','5000','role="dialog"'])assert.match(ui,new RegExp(expected));assert.match(delta,/api\.india\.delta\.exchange/);assert.match(delta,/cdn-ind\.testnet\.deltaex\.org/);assert.match(worker,/PORTFOLIO_RUNTIME_ID/);assert.match(worker,/TradingRuntimeManager/);});

test('portfolio repository uses exact collection and compound unique index',()=>{const source=fs.readFileSync(path.join(process.cwd(),'lib/portfolio/repository.ts'),'utf8');assert.match(source,/collection<PortfolioDocument>\('portfolio'\)/);assert.match(source,/createIndex\(\{environment:1,symbol:1\},\{unique:true,name:'portfolio_environment_symbol_unique'\}\)/);});
