import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { ObjectId } from 'mongodb';
import { NextRequest } from 'next/server';
import { createPortfolio,normalizePortfolioEnvironment,normalizePortfolioSymbol,portfolioDeletionUiState,sanitizePortfolio,type PortfolioDependencies } from '../lib/portfolio/service';
import { DELETE,GET,POST } from '../app/api/portfolio/route';
import { isPortfolioDeleteDisabled } from '../components/portfolio-delete-eligibility';
import { claimPortfolioDeletion,releasePortfolioDeletion,removeDeletedPortfolio,requestPortfolioDeletion } from '../components/portfolio-delete-client';

test('portfolio APIs require authentication before portfolio or Delta access',async()=>{assert.equal((await GET(new NextRequest('http://localhost/api/portfolio'))).status,401);assert.equal((await POST(new NextRequest('http://localhost/api/portfolio',{method:'POST',headers:{origin:'http://localhost','content-type':'application/json'},body:JSON.stringify({symbol:'XAUTUSD',environment:'demo'})}))).status,401);assert.equal((await DELETE(new NextRequest('http://localhost/api/portfolio',{method:'DELETE'}))).status,401);});

test('portfolio symbols normalize whitespace and case and reject unsafe input',()=>{assert.equal(normalizePortfolioSymbol('  xautusd  '),'XAUTUSD');assert.throws(()=>normalizePortfolioSymbol('   '),/SYMBOL_REQUIRED/);for(const value of ['BTC/USD','BTC USD','BTC$USD','A'.repeat(31)])assert.throws(()=>normalizePortfolioSymbol(value),/SYMBOL_FORMAT/);});
test('portfolio environment accepts only the stable real and demo enum',()=>{assert.equal(normalizePortfolioEnvironment('real'),'real');assert.equal(normalizePortfolioEnvironment('demo'),'demo');for(const value of ['live','production','testnet','REAL',undefined])assert.throws(()=>normalizePortfolioEnvironment(value),/ENVIRONMENT_REQUIRED/);});

function memoryPortfolio(product:(symbol:string,environment:'real'|'demo')=>Promise<any>){const documents:any[]=[];let productCalls=0;const dependencies:PortfolioDependencies={find:async(environment,symbol)=>documents.find(row=>row.environment===environment&&row.symbol===symbol)??null,insert:async(document:any)=>{if(documents.some(row=>row.environment===document.environment&&row.symbol===document.symbol)){const error:any=new Error('duplicate');error.code=11000;throw error;}const saved={...document,_id:new ObjectId()};documents.push(saved);return saved;},product:async(symbol,environment)=>{productCalls++;return product(symbol,environment);},now:()=>new Date('2026-09-01T00:00:00.000Z')};return {documents,dependencies,get productCalls(){return productCalls;}};}

test('valid Delta product creates one normalized stable portfolio in the selected environment',async()=>{let selected='';const memory=memoryPortfolio(async(symbol,environment)=>{selected=environment;return{id:181689,symbol,description:'Gold Futures',contract_value:'0.001',settling_asset:{symbol:'USD'},underlying_asset:{symbol:'XAUT'}};});const saved=await createPortfolio(' xautusd ','demo',memory.dependencies);assert.equal(saved.symbol,'XAUTUSD');assert.equal(saved.environment,'demo');assert.equal(selected,'demo');assert.equal(saved.productId,181689);assert.equal(saved.contractValue,0.001);assert.equal(memory.documents.length,1);await assert.rejects(()=>createPortfolio('XAUTUSD','demo',memory.dependencies),/PORTFOLIO_EXISTS/);assert.equal(memory.documents.length,1);assert.equal(memory.productCalls,1);});

test('nonexistent or unverifiable Delta products never create portfolio records',async()=>{for(const product of [async()=>{throw new Error('product_not_found');},async()=>{throw new Error('DELTA_NETWORK_TIMEOUT');},async()=>({id:2,symbol:'OTHER'})]){const memory=memoryPortfolio(product);await assert.rejects(()=>createPortfolio('BTCUSDD','real',memory.dependencies),/SYMBOL_NOT_FOUND|DELTA_VERIFICATION_FAILED/);assert.equal(memory.documents.length,0);}});

test('portfolio response is sanitized and UI provides environments, prices, refresh, deletion, and runtime routing',()=>{const row:any={_id:new ObjectId(),symbol:'XAUTUSD',productId:181689,name:'Gold',contractValue:0.001,settlingAsset:'USD',underlyingAsset:'XAUT',environment:'demo',createdAt:new Date(),updatedAt:new Date(),secret:'never'};const output:any=sanitizePortfolio(row);assert.equal(output.secret,undefined);assert.equal(JSON.stringify(output).includes('never'),false);const ui=fs.readFileSync(path.join(process.cwd(),'components/PortfolioManager.tsx'),'utf8'),worker=fs.readFileSync(path.join(process.cwd(),'worker.ts'),'utf8'),delta=fs.readFileSync(path.join(process.cwd(),'lib/delta.ts'),'utf8');for(const expected of ['Add Portfolio','Trading Environment','Current Price','DELETE','setInterval','5000','role="dialog"'])assert.match(ui,new RegExp(expected));assert.match(delta,/api\.india\.delta\.exchange/);assert.match(delta,/cdn-ind\.testnet\.deltaex\.org/);assert.match(worker,/PORTFOLIO_RUNTIME_ID/);assert.match(worker,/TradingRuntimeManager/);});

test('portfolio repository uses exact collection and compound unique index',()=>{const source=fs.readFileSync(path.join(process.cwd(),'lib/portfolio/repository.ts'),'utf8');assert.match(source,/collection<PortfolioDocument>\('portfolio'\)/);assert.match(source,/createIndex\(\{environment:1,symbol:1\},\{unique:true,name:'portfolio_environment_symbol_unique'\}\)/);});
test('portfolio UI deletion state enables safe flat and stale-cache portfolios but explains concrete active state',()=>{const row:any={_id:new ObjectId()};assert.equal(portfolioDeletionUiState(row,{position:{size:0},running:false,activeTrade:null,pending:null}).allowed,true);const active=portfolioDeletionUiState(row,{position:{size:2},running:false});assert.equal(active.allowed,false);assert.match(String(active.reason),/open position is being managed/);assert.equal(portfolioDeletionUiState(row,{running:false}).allowed,true);});
test('robot on with zero position leaves portfolio Delete enabled',()=>{const state=portfolioDeletionUiState({} as any,{position:{size:0},running:true,activeTrade:null,pending:null});assert.equal(state.allowed,true);assert.equal(isPortfolioDeleteDisabled(state,false),false);});
test('robot off with zero position leaves portfolio Delete enabled',()=>{const state=portfolioDeletionUiState({} as any,{position:{size:0},running:false,activeTrade:null,pending:null});assert.equal(isPortfolioDeleteDisabled(state,false),false);});
test('known non-zero position disables portfolio Delete regardless of robot state',()=>{for(const running of [true,false])assert.equal(isPortfolioDeleteDisabled(portfolioDeletionUiState({} as any,{position:{size:2},running}),false),true);});
test('portfolio deletion in progress disables Delete',()=>{assert.equal(isPortfolioDeleteDisabled({allowed:true,positionKnown:true,positionSize:0},true),true);});
test('numeric and API-normalized string zero both enable Delete',()=>{for(const positionSize of [0,'0','0.0'])assert.equal(isPortfolioDeleteDisabled({allowed:true,positionKnown:true,positionSize},false),false);});
test('explicit server eligibility controls Delete instead of stale position-known cache',()=>{assert.equal(isPortfolioDeleteDisabled(undefined,false),true);assert.equal(isPortfolioDeleteDisabled({allowed:true,positionKnown:false,positionSize:null},false),false);assert.equal(isPortfolioDeleteDisabled({allowed:false,positionKnown:true,positionSize:0},false),true);});

test('successful delete request removes only its portfolio from client state',async()=>{let calls=0;const request=async(input:any,init?:RequestInit)=>{calls++;assert.equal(input,'/api/portfolio');assert.equal(init?.method,'DELETE');assert.equal((init?.headers as any)['x-csrf-token'],'csrf');assert.deepEqual(JSON.parse(String(init?.body)),{id:'delete-me'});return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json'}});};await requestPortfolioDeletion('delete-me','csrf',request as typeof fetch);assert.equal(calls,1);assert.deepEqual(removeDeletedPortfolio([{id:'keep'},{id:'delete-me'}],'delete-me'),[{id:'keep'}]);});
test('synchronous deletion claim prevents double delete and releases after completion',()=>{const ref={current:''};assert.equal(claimPortfolioDeletion(ref,'one'),true);assert.equal(claimPortfolioDeletion(ref,'one'),false);assert.equal(claimPortfolioDeletion(ref,'two'),false);releasePortfolioDeletion(ref);assert.equal(claimPortfolioDeletion(ref,'two'),true);});
test('backend delete failure preserves useful error for UI and permits retry',async()=>{await assert.rejects(()=>requestPortfolioDeletion('one','csrf',async()=>new Response(JSON.stringify({error:'Close the active position before deleting this portfolio.'}),{status:409,headers:{'content-type':'application/json'}}) as any),/Close the active position/);const ref={current:'one'};releasePortfolioDeletion(ref);assert.equal(claimPortfolioDeletion(ref,'one'),true);});
