import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { GET } from '../app/api/health/route';
import { supervisorHealthResponse } from '../lib/runtime/supervision-health';

const root=process.cwd(),read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');

test('unauthenticated health endpoint is fast, minimal, and read only',async()=>{const response=GET();assert.equal(response.status,200);assert.deepEqual(await response.json(),{status:'ok'});const source=read('app/api/health/route.ts');for(const forbidden of ['requireApiSession','getPosition','getOpenOrders','placeMarketOrder','placeBracket','MONGODB_URI','AUTH_SECRET','API_KEY','API_SECRET'])assert.equal(source.includes(forbidden),false);});
test('health remains healthy for recovery and becomes unhealthy only for terminal supervision failure',()=>{for(const temporaryState of [false,false,false])assert.equal(supervisorHealthResponse(temporaryState).status,200);assert.deepEqual(supervisorHealthResponse(true),{status:503,body:{status:'unhealthy'}});});
test('Render blueprint starts one supervised web service with the health endpoint',()=>{const render=read('render.yaml'),pkg=JSON.parse(read('package.json'));assert.match(render,/type: web/);assert.match(render,/buildCommand: npm ci && npm run build/);assert.match(render,/startCommand: npm start/);assert.match(render,/healthCheckPath: \/api\/health/);assert.match(pkg.scripts.start,/concurrently --kill-others-on-fail/);assert.match(pkg.scripts.start,/next start/);assert.match(pkg.scripts.start,/tsx worker\.ts/);});
test('worker shutdown blocks new entries and does not alter durable trades or protection',()=>{const source=read('worker.ts'),main=source.slice(source.indexOf('async function main()')),manage=source.slice(source.indexOf('async function manage()'));assert.match(main,/SIGTERM/);assert.match(main,/SIGINT/);assert.match(main,/while \(!shuttingDown\)/);assert.match(source,/robotRunning:\(\)=>!shuttingDown/);assert.match(source,/portfolioEntryAllowed:async\(\)=>!shuttingDown/);for(const forbidden of ['deletePortfolio','initialSL:null','takeProfit:null','cancelAll'])assert.equal(manage.includes(forbidden),false);});
test('restart path retains portfolio restoration and five-second protection monitoring',()=>{const source=read('worker.ts');assert.match(source,/TradingRuntimeManager\(listPortfolio,spawnPortfolioWorker\)/);assert.match(source,/findOpenBotTrade/);assert.match(source,/findOpenManualTrades/);assert.match(source,/restoreOpenBotTrade/);assert.match(source,/syncExchangeBracket\(\)/);assert.match(source,/const BRACKET_SYNC_MS = 5_000/);assert.match(read('lib/config.ts'),/pollMs: Number\(process\.env\.POLL_MS \|\| 1000\)/);});
test('temporary Delta failures remain recoverable and do not affect health',()=>{const source=read('worker.ts'),loop=source.slice(source.indexOf('while (!shuttingDown)'));assert.match(loop,/deltaErrorDetails/);assert.match(loop,/Keep the worker alive/);assert.doesNotMatch(read('app/api/health/route.ts'),/Delta|connectionState|offline/);});
test('fatal startup and repeated runtime death exit non-zero for Render supervision',()=>{const source=read('worker.ts');assert.match(source,/RuntimePermanentlyDeadError/);assert.match(source,/writeSupervisorHealth\(true\)/);assert.match(source,/shutdown\(1\)/);assert.match(source,/runtimeStartupExitCode\(error\)/);assert.match(source,/process\.exit\(exitCode\)/);});
