import assert from 'node:assert/strict';
import test from 'node:test';
import { ObjectId } from 'mongodb';
import { acquireLease,entryLeaseKey,portfolioEntryLeaseKey,releaseLease,renewLease,verifyLeaseOwnership,type LeaseCollection,type RuntimeLease } from '../lib/runtime/leases';
import { withExecutionActivity } from '../lib/runtime/entry-coordinator';
import { deletePortfolioCoordinated,verifyPortfolioDeletion } from '../lib/portfolio/deletion';
import { legacyPositionRequiresReconciliation } from '../lib/runtime/legacy-guard';

class MemoryLocks implements LeaseCollection{
  rows=new Map<string,any>();
  async findOne(filter:any){const current=this.rows.get(filter._id);if(!current||current.ownerId!==filter.ownerId||current.expiresAt<=filter.expiresAt.$gt)return null;return current;}
  async findOneAndUpdate(filter:any,update:any){const current=this.rows.get(filter._id),now=filter.$or[0].expiresAt.$lte,allowed=!current||current.expiresAt<=now||current.ownerId===filter.$or[1].ownerId;if(!allowed){const error:any=new Error('duplicate');error.code=11000;throw error;}const next={...(current||{}),_id:filter._id,...update.$set};this.rows.set(filter._id,next);return next;}
  async updateOne(filter:any,update:any){const current=this.rows.get(filter._id);if(!current||current.ownerId!==filter.ownerId||current.expiresAt<=filter.expiresAt.$gt)return{modifiedCount:0};this.rows.set(filter._id,{...current,...update.$set});return{modifiedCount:1};}
  async deleteOne(filter:any){const current=this.rows.get(filter._id);if(!current||current.ownerId!==filter.ownerId)return{deletedCount:0};this.rows.delete(filter._id);return{deletedCount:1};}
}
const clock=(value:number)=>({now:()=>new Date(value)});

test('same-environment account entries serialize and second sees margin updated by first',async()=>{const locks=new MemoryLocks(),first=await acquireLease(entryLeaseKey('demo'),'btc',30_000,'demo',locks,clock(1_000));assert.ok(first);assert.equal(await acquireLease(entryLeaseKey('demo'),'xaut',30_000,'demo',locks,clock(1_001)),null);let margin=1_000;const firstSizeMargin=margin;margin=800;await releaseLease(first!,locks);const second=await acquireLease(entryLeaseKey('demo'),'xaut',30_000,'demo',locks,clock(1_002));assert.ok(second);const secondSizeMargin=margin;assert.equal(firstSizeMargin,1_000);assert.equal(secondSizeMargin,800);});

test('REAL and DEMO account entry locks are independent',async()=>{const locks=new MemoryLocks();const real=await acquireLease(entryLeaseKey('real'),'real-worker',30_000,'real',locks,clock(1_000)),demo=await acquireLease(entryLeaseKey('demo'),'demo-worker',30_000,'demo',locks,clock(1_000));assert.ok(real);assert.ok(demo);assert.notEqual(real?.key,demo?.key);});

test('expired process-safe lease can be recovered but an active lease cannot',async()=>{const locks=new MemoryLocks();assert.ok(await acquireLease('portfolio-runtime:p1','manager-one',100,'real',locks,clock(1_000)));assert.equal(await acquireLease('portfolio-runtime:p1','manager-two',100,'real',locks,clock(1_050)),null);assert.ok(await acquireLease('portfolio-runtime:p1','manager-two',100,'real',locks,clock(1_101)));});

test('owner renewal extends expiry and keeps a second same-environment worker out beyond the original TTL',async()=>{const locks=new MemoryLocks(),first=await acquireLease(entryLeaseKey('demo'),'worker-a',90,'demo',locks,clock(1_000));assert.ok(first);assert.equal(await renewLease(first!,90,locks,clock(1_060)),true);assert.equal(locks.rows.get(entryLeaseKey('demo')).expiresAt.valueOf(),1_150);assert.equal(await acquireLease(entryLeaseKey('demo'),'worker-b',90,'demo',locks,clock(1_100)),null);assert.ok(await acquireLease(entryLeaseKey('demo'),'worker-b',90,'demo',locks,clock(1_151)));});
test('wrong owner cannot renew and valid, expired, missing, and wrong-owner verification are authoritative',async()=>{const locks=new MemoryLocks(),lease=await acquireLease(entryLeaseKey('real'),'owner',100,'real',locks,clock(1_000));assert.ok(lease);assert.equal(await renewLease({...lease!,ownerId:'wrong'},100,locks,clock(1_010)),false);assert.equal(await verifyLeaseOwnership(lease!,locks,clock(1_050)),true);assert.equal(await verifyLeaseOwnership({...lease!,ownerId:'wrong'},locks,clock(1_050)),false);assert.equal(await verifyLeaseOwnership(lease!,locks,clock(1_101)),false);assert.equal(await verifyLeaseOwnership({key:'missing',ownerId:'owner'},locks,clock(1_050)),false);});

test('entry heartbeat renews, reports ownership loss once, and always stops before release',async()=>{const lease={key:'entry',ownerId:'owner',acquiredAt:new Date(),expiresAt:new Date()} as RuntimeLease,events:string[]=[],order:string[]=[];let tick:(()=>void)|null=null,renewals=0;await assert.rejects(()=>withExecutionActivity(lease,'portfolio',async context=>{tick?.();await new Promise(resolve=>setImmediate(resolve));assert.equal(renewals,1);tick?.();await new Promise(resolve=>setImmediate(resolve));assert.equal(context.ownershipLost(),true);await context.assertOwnership();},{activity:value=>order.push(`activity:${value.executionInProgress}`),release:async()=>{order.push('release');return true;},renew:async()=>++renewals===1,verify:async()=>true,setTimer:callback=>{tick=callback;return 1 as any;},clearTimer:()=>order.push('timer-cleared')},{leaseMs:90,heartbeatMs:25,onLeaseLost:()=>events.push('lost')}),/ACCOUNT_ENTRY_LEASE_LOST/);assert.deepEqual(events,['lost']);assert.deepEqual(order,['activity:true','timer-cleared','activity:false','release']);});

for(const outcome of ['success','risk rejection','Robot Stop','AUTO_TRADE OFF','market-order exception','ambiguous market-order timeout'])test(`entry heartbeat stops and lease releases after ${outcome}`,async()=>{const lease={key:'entry',ownerId:'owner',acquiredAt:new Date(),expiresAt:new Date()} as RuntimeLease,cleanup:string[]=[];const run=()=>withExecutionActivity(lease,'portfolio',async()=>{if(outcome==='success')return true;throw new Error(outcome);},{activity:()=>{},release:async()=>{cleanup.push('release');return true;},setTimer:()=>1 as any,clearTimer:()=>cleanup.push('timer')});if(outcome==='success')await run();else await assert.rejects(run);assert.deepEqual(cleanup,['timer','release']);});

for(const failure of ['setLeverage exception','Stop Robot second check','market-order exception','bracket exception'])test(`executionInProgress resets after ${failure}`,async()=>{const activity:boolean[]=[],lease={key:'entry',ownerId:'owner',acquiredAt:new Date(),expiresAt:new Date()} as RuntimeLease;await assert.rejects(()=>withExecutionActivity(lease,'portfolio',async()=>{throw new Error(failure);},{activity:value=>activity.push(value.executionInProgress),release:async()=>true}),new RegExp(failure));assert.deepEqual(activity,[true,false]);});
test('executionInProgress resets after successful entry workflow',async()=>{const activity:boolean[]=[],lease={key:'entry',ownerId:'owner',acquiredAt:new Date(),expiresAt:new Date()} as RuntimeLease;assert.equal(await withExecutionActivity(lease,'portfolio',async()=>42,{activity:value=>activity.push(value.executionInProgress),release:async()=>true}),42);assert.deepEqual(activity,[true,false]);});

function portfolio(){return {_id:new ObjectId(),symbol:'BTCUSD',productId:27,environment:'demo' as const,name:null,contractValue:0.001,settlingAsset:'USD',underlyingAsset:'BTC',createdAt:new Date(),updatedAt:new Date()};}
function deletionDeps(overrides:Partial<any>={}){return {status:()=>({running:false,position:{size:0},activeTrade:null,pending:null}),activity:()=>({executionInProgress:false}),hasActiveTrades:async()=>false,blockingIntent:async()=>null,position:async()=>({size:0}),openOrders:async()=>[],...overrides};}
test('fresh Delta nonzero/manual position blocks deletion even when cached status is flat',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({position:async()=>({size:'2'})})),{ok:false,reason:'ACTIVE'});});
test('Delta position lookup failure blocks deletion conservatively',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({position:async()=>{throw new Error('offline');}})),{ok:false,reason:'VERIFICATION_FAILED'});});
test('fresh flat Delta state and no runtime activity permits deletion',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps()),{ok:true});});
test('Robot running and an untriggered pending setup do not block coordinated safe deletion',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({status:()=>({running:true,position:{size:0},activeTrade:null,pending:{direction:'long'}})})),{ok:true});});
test('entry execution in progress and durable active trade still block deletion',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({activity:()=>({executionInProgress:true})})),{ok:false,reason:'ACTIVE'});assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({hasActiveTrades:async()=>true})),{ok:false,reason:'ACTIVE'});});
test('fresh product open orders block deletion',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({openOrders:async()=>[{id:'order'}]})),{ok:false,reason:'ACTIVE'});});
test('ambiguous or submitting durable entry intent blocks deletion',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({blockingIntent:async()=>({state:'AMBIGUOUS'})})),{ok:false,reason:'ENTRY_UNRESOLVED'});});
test('completed entry intent does not permanently block deletion',async()=>{assert.deepEqual(await verifyPortfolioDeletion(portfolio(),deletionDeps({blockingIntent:async()=>null})),{ok:true});});
test('delete and entry share one portfolio-scoped cross-process mutex',async()=>{const locks=new MemoryLocks(),row=portfolio(),id=row._id.toHexString(),entry=await acquireLease(portfolioEntryLeaseKey(id),'entry',30_000,'demo',locks,clock(1_000));assert.ok(entry);let removed=false;const common={owns:(lease:RuntimeLease)=>verifyLeaseOwnership(lease,locks,clock(1_001)),release:(lease:RuntimeLease)=>releaseLease(lease,locks),verify:async()=>({ok:true as const})};const blocked=await deletePortfolioCoordinated(row,async()=>{removed=true;return true},{...common,acquire:(key,owner,ms)=>acquireLease(key,owner,ms,'demo',locks,clock(1_001))});assert.deepEqual(blocked,{ok:false,reason:'IN_PROGRESS'});assert.equal(removed,false);await releaseLease(entry!,locks);const deleted=await deletePortfolioCoordinated(row,async()=>{removed=true;return true},{...common,acquire:(key,owner,ms)=>acquireLease(key,owner,ms,'demo',locks,clock(1_002)),owns:lease=>verifyLeaseOwnership(lease,locks,clock(1_002))});assert.deepEqual(deleted,{ok:true});assert.equal(removed,true);});
test('portfolio deletion mutexes are isolated by portfolio id and survive process boundaries until expiry/release',async()=>{const locks=new MemoryLocks();assert.ok(await acquireLease(portfolioEntryLeaseKey('a'),'delete-a',100,'demo',locks,clock(1_000)));assert.ok(await acquireLease(portfolioEntryLeaseKey('b'),'entry-b',100,'demo',locks,clock(1_000)));assert.equal(await acquireLease(portfolioEntryLeaseKey('a'),'entry-a',100,'demo',locks,clock(1_050)),null);assert.ok(await acquireLease(portfolioEntryLeaseKey('a'),'entry-a',100,'demo',locks,clock(1_101)));});
test('legacy unscoped unresolved trade with same-product live position activates migration guard',()=>{assert.equal(legacyPositionRequiresReconciliation(2,[{tradeId:'legacy-open',status:'OPEN'}]),true);assert.equal(legacyPositionRequiresReconciliation(0,[{tradeId:'legacy-open',status:'OPEN'}]),false);});

test('worker acquires account lock before product position and margin refresh',()=>{const source=require('node:fs').readFileSync(require('node:path').join(process.cwd(),'worker.ts'),'utf8'),lock=source.indexOf('acquireAccountEntryLease'),position=source.indexOf('refreshPosition(lastPrice, true)',lock),margin=source.indexOf('refreshWallet(true)',lock);assert.ok(lock>=0&&position>lock&&margin>position);assert.match(source,/LEGACY_TRADE_REQUIRES_PORTFOLIO_RECONCILIATION/);});
test('worker proves lease ownership immediately inside the durable-intent submission callback before market order',()=>{const source=require('node:fs').readFileSync(require('node:path').join(process.cwd(),'worker.ts'),'utf8');assert.match(source,/submitPreparedEntryIntent\(intent,async clientOrderId=>\{await entryExecution\.assertOwnership\(\);addTradeEvent\('ENTRY_SUBMISSION_STARTED'[\s\S]*?placeMarketOrder/);assert.match(source,/heartbeatMs:25_000/);assert.match(source,/ACCOUNT_ENTRY_LEASE_LOST/);});
