import assert from 'node:assert/strict';
import test from 'node:test';
import { NextRequest } from 'next/server';
import { aggregateCommission, applyDailyLossOutcome, attributeTradeFills, classifyBotExitEvidence, deltaTimestampMilliseconds, financials, findBotCloseBoundary, findTradeCloseBoundary, grossPnL, resolvePositionOwnership, stableTradeId, weightedAverage } from '../lib/trades/reconciliation';
import { boundedHistory, toDeltaMicroseconds } from '../lib/delta';
import { persistClosedTrade, persistOpenBotTrade, persistOpenManualTrade, type TradePersistenceDependencies } from '../lib/trades/persistence';
import { calculateStats } from '../lib/trades/statistics';
import type { TradeDocument } from '../models/Trade';

const row=(source:'bot'|'exchange_existing',gross:number,brokerage:number|null,GST:number|null):TradeDocument=>({tradeId:`${source}-${gross}`,symbol:'XAUTUSD',productId:1,side:'LONG',source,attributionStatus:source==='bot'?'BOT_CONFIRMED':'MANUAL_CONFIRMED',status:'CLOSED',entryTime:new Date(),intendedEntryPrice:100,actualEntryPrice:100,quantity:1,contracts:1,contractValue:1,initialSL:90,takeProfit:120,exitTime:new Date(),intendedExitPrice:100+gross,actualExitPrice:100+gross,exitReason:'UNKNOWN',grossPnL:gross,brokerage,GST,otherCharges:GST==null?null:0,totalCharges:brokerage!=null&&GST!=null?brokerage+GST:null,netPnL:brokerage!=null&&GST!=null?gross-brokerage-GST:null,estimatedBrokerage:null,estimatedGST:null,estimatedTotalCharges:null,estimatedNetPnL:null,realizedR:brokerage!=null&&GST!=null?gross/10:null,entryOrderId:'1',exitOrderId:'2',entryClientOrderId:null,exitClientOrderId:null,entryFillIds:['1'],exitFillIds:['2'],financialStatus:brokerage!=null&&GST!=null?'actual':'partial',feeDataSource:'delta_fills_commission',priceDataSource:'delta_weighted_fills',attributionNote:null,reconciliationError:null,createdAt:new Date(),updatedAt:new Date(),reconciledAt:new Date()});

test('LONG and SHORT gross P/L signs are correct',()=>{assert.equal(grossPnL('LONG',100,110,2),20);assert.equal(grossPnL('LONG',100,90,2),-20);assert.equal(grossPnL('SHORT',100,90,2),20);assert.equal(grossPnL('SHORT',100,110,2),-20);});
test('weighted fills and actual commission aggregate once',()=>{const fills=[{price:'100',size:1,commission:'0.1'},{price:'110',size:3,commission:'0.2'}];assert.equal(weightedAverage(fills),107.5);assert.ok(Math.abs((aggregateCommission(fills)??0)-0.3)<1e-12);});
test('actual and estimated charges are never silently mixed',()=>{const value=financials({side:'LONG',entry:100,exit:110,quantity:2,entryFills:[{commission:'0.1'}],exitFills:[{commission:'0.2'}],estimatedBrokerage:0.5,estimatedGST:0.09});assert.equal(value.brokerage,0.30000000000000004);assert.equal(value.GST,null);assert.equal(value.totalCharges,null);assert.equal(value.netPnL,null);assert.equal(value.estimatedTotalCharges,0.59);assert.equal(value.financialStatus,'partial');});
test('missing financial data does not create fake actual values',()=>{const value=financials({side:'LONG',entry:100,exit:110,quantity:1,entryFills:[],exitFills:[]});assert.equal(value.brokerage,null);assert.equal(value.GST,null);assert.equal(value.netPnL,null);});
test('unknown commission stays unknown and estimates remain separate',()=>{const value=financials({side:'LONG',entry:100,exit:110,quantity:1,entryFills:[{commission:'0.1'}],exitFills:[{}],estimatedBrokerage:0.25,estimatedGST:0.045});assert.equal(value.brokerage,null);assert.equal(value.estimatedBrokerage,0.25);assert.equal(value.GST,null);assert.equal(value.estimatedGST,0.045);assert.equal(value.financialStatus,'partial');});
test('stable exchange identity is deterministic and never timestamp-only',()=>{assert.equal(stableTradeId('bot',1,null,[],[]),null);assert.equal(stableTradeId('bot',1,'99',[],[]),stableTradeId('bot',1,'99',[],[]));assert.notEqual(stableTradeId('bot',1,'99',[],[]),stableTradeId('exchange_existing',1,'99',[],[]));});
test('bot/manual/account statistics remain separate and additive',()=>{const rows=[row('bot',10,1,0.18),row('bot',-5,0.5,0.09),row('exchange_existing',8,0.8,0.144)];const bot=calculateStats(rows,'bot'),manual=calculateStats(rows,'exchange_existing'),account=calculateStats(rows);assert.equal(bot.totalTrades,2);assert.equal(manual.totalTrades,1);assert.equal(account.totalTrades,bot.totalTrades+manual.totalTrades);assert.equal(account.winningTrades,bot.winningTrades+manual.winningTrades);assert.equal(account.losingTrades,bot.losingTrades+manual.losingTrades);for(const key of ['grossPnL','brokerage','GST','totalCharges','netPnL'] as const)assert.ok(Math.abs(account[key]-bot[key]-manual[key])<1e-12, key);});
test('trade APIs reject unauthenticated requests before database access',async()=>{const history=await import('../app/api/trades/route');const stats=await import('../app/api/trades/stats/route');assert.equal((await history.GET(new NextRequest('http://localhost/api/trades'))).status,401);assert.equal((await stats.GET(new NextRequest('http://localhost/api/trades/stats'))).status,401);});

const botOrder={id:'entry',client_order_id:'ema-123',product_id:1,side:'buy'};
const fill=(id:string,order_id:string,side:'buy'|'sell',size:number,second:number,commission='0.1')=>({id,order_id,product_id:1,side,size,price:side==='buy'?100:110,commission,created_at:new Date(second*1000).toISOString()});
test('ownership lookup failure is never classified manual',()=>{assert.equal(resolvePositionOwnership({lookupFailed:true,currentSize:5,productId:1,persisted:null,fills:[],orders:[],historyComplete:false}).status,'LOOKUP_FAILED');});
test('valid persisted bot ownership requires order and uninterrupted fills',()=>{const result=resolvePositionOwnership({lookupFailed:false,currentSize:5,productId:1,persisted:{entryOrderId:'entry',entryClientOrderId:'ema-123',entryTime:new Date(1000),side:'LONG',contracts:5},fills:[fill('e','entry','buy',5,2)],orders:[botOrder],historyComplete:true});assert.equal(result.status,'BOT_CONFIRMED');assert.equal(result.botOwnedContracts,5);});
test('direction match alone cannot restore bot and stale lifecycle cannot claim manual position',()=>{const persisted={entryOrderId:'entry',entryClientOrderId:'ema-123',entryTime:new Date(1000),side:'LONG' as const,contracts:5};assert.equal(resolvePositionOwnership({lookupFailed:false,currentSize:5,productId:1,persisted,fills:[],orders:[botOrder],historyComplete:true}).status,'UNKNOWN');const stale=resolvePositionOwnership({lookupFailed:false,currentSize:5,productId:1,persisted,fills:[fill('e','entry','buy',5,2),fill('x','close','sell',5,3),fill('m','manual','buy',5,4)],orders:[botOrder,{id:'close',product_id:1},{id:'manual',product_id:1,client_order_id:'manual'}],historyComplete:true});assert.equal(stale.status,'UNKNOWN');assert.equal(stale.staleBotClosed,true);});
test('complete non-bot lifecycle can be classified manual',()=>{const result=resolvePositionOwnership({lookupFailed:false,currentSize:2,productId:1,persisted:null,fills:[fill('m','manual','buy',2,4)],orders:[{id:'manual',product_id:1,client_order_id:'user-order'}],historyComplete:true});assert.equal(result.status,'MANUAL_CONFIRMED');});
test('multiple fully mapped non-bot opening fills can be classified manual',()=>{const result=resolvePositionOwnership({lookupFailed:false,currentSize:4,productId:1,persisted:null,fills:[fill('m1','manual-1','buy',2,3),fill('m2','manual-2','buy',2,4)],orders:[{id:'manual-1',product_id:1,client_order_id:'user-order-1'},{id:'manual-2',product_id:1,client_order_id:'user-order-2'}],historyComplete:true});assert.equal(result.status,'MANUAL_CONFIRMED');});
test('partially mapped opening lifecycle remains unknown',()=>{const result=resolvePositionOwnership({lookupFailed:false,currentSize:4,productId:1,persisted:null,fills:[fill('m1','manual-1','buy',2,3),fill('unresolved','missing-order','buy',2,4)],orders:[{id:'manual-1',product_id:1,client_order_id:'user-order-1'}],historyComplete:true});assert.equal(result.status,'UNKNOWN');assert.equal(result.botOwnedContracts,0);});
test('mapped opening order without a client identity remains unknown',()=>{const result=resolvePositionOwnership({lookupFailed:false,currentSize:2,productId:1,persisted:null,fills:[fill('m','manual','buy',2,4)],orders:[{id:'manual',product_id:1}],historyComplete:true});assert.equal(result.status,'UNKNOWN');});
test('mixed bot and manual opening orders remain unknown',()=>{const result=resolvePositionOwnership({lookupFailed:false,currentSize:4,productId:1,persisted:null,fills:[fill('b','bot-entry','buy',2,3),fill('m','manual-entry','buy',2,4)],orders:[{id:'bot-entry',product_id:1,client_order_id:'ema-123'},{id:'manual-entry',product_id:1,client_order_id:'user-order'}],historyComplete:true});assert.equal(result.status,'UNKNOWN');assert.equal(result.botOwnedContracts,0);});
test('opening-order lookup failure remains lookup failed despite otherwise complete evidence',()=>{const result=resolvePositionOwnership({lookupFailed:true,currentSize:2,productId:1,persisted:null,fills:[fill('m','manual','buy',2,4)],orders:[{id:'manual',product_id:1,client_order_id:'user-order'}],historyComplete:true});assert.equal(result.status,'LOOKUP_FAILED');});
test('unresolved opening ownership cannot persist fabricated financial attribution',async()=>{const ownership=resolvePositionOwnership({lookupFailed:false,currentSize:4,productId:1,persisted:null,fills:[fill('m','manual-1','buy',2,3),fill('u','missing-order','buy',2,4)],orders:[{id:'manual-1',product_id:1,client_order_id:'user-order'}],historyComplete:true});let upserts=0;const dependencies:TradePersistenceDependencies={upsert:(async()=>{upserts++;}) as any,fills:(async()=>({result:[],complete:true})) as any,orders:(async()=>({result:[],complete:true})) as any,now:()=>5000};await assert.rejects(()=>persistClosedTrade({direction:'long',source:'unattributed' as any,attributionStatus:ownership.status,contracts:4,ownedContracts:0,contractValue:1},1,'XAUTUSD',null,dependencies),/RECONCILIATION_UNRESOLVED/);assert.equal(upserts,0);});
test('strict fill attribution accepts exact multiple bot exits',()=>{const result=attributeTradeFills({source:'bot',side:'LONG',productId:1,ownedContracts:5,entryOrderId:'entry',fills:[fill('e','entry','buy',5,2),fill('x1','exit1','sell',2,3),fill('x2','exit2','sell',3,4)],orders:[botOrder,{id:'exit1',product_id:1,reduce_only:true},{id:'exit2',product_id:1,stop_order_type:'take_profit_order'}],windowStart:1000,windowEnd:5000,historyComplete:true,mixedPosition:false});assert.equal(result.complete,true);assert.equal(weightedAverage(result.exitFills),110);assert.ok(Math.abs((aggregateCommission([...result.entryFills,...result.exitFills])??0)-0.3)<1e-12);});
test('unrelated, outside-window, wrong-order and oversized exit fills are rejected',()=>{const base={source:'bot' as const,side:'LONG' as const,productId:1,ownedContracts:5,entryOrderId:'entry',orders:[botOrder,{id:'exit',product_id:1,reduce_only:true}],windowStart:1000,windowEnd:5000,historyComplete:true,mixedPosition:false};assert.equal(attributeTradeFills({...base,fills:[fill('e','entry','buy',5,2),fill('outside','exit','sell',5,9)]}).complete,false);assert.equal(attributeTradeFills({...base,fills:[fill('e','entry','buy',5,2),fill('wrong','missing','sell',5,3)]}).complete,false);assert.equal(attributeTradeFills({...base,fills:[fill('e','entry','buy',5,2),fill('large','exit','sell',7,3)]}).ambiguous,true);assert.equal(attributeTradeFills({...base,fills:[fill('e','entry','buy',5,2),fill('u','exit','sell',1,3),fill('x','exit','sell',5,4)]}).complete,false);});
test('mixed bot five plus manual two never attributes seven-contract actual fees',()=>{const result=attributeTradeFills({source:'bot',side:'LONG',productId:1,ownedContracts:5,entryOrderId:'entry',fills:[fill('e','entry','buy',5,2),fill('m','manual','buy',2,3),fill('x','exit','sell',7,4)],orders:[botOrder,{id:'manual',product_id:1},{id:'exit',product_id:1,reduce_only:true}],windowStart:1000,windowEnd:5000,historyComplete:true,mixedPosition:true});assert.equal(result.complete,false);assert.deepEqual(result.exitFills,[]);});
test('manual transition rejects additions and ambiguous lifecycle activity',()=>{const result=attributeTradeFills({source:'exchange_existing',side:'LONG',productId:1,ownedContracts:5,entryOrderId:null,fills:[fill('add','add','buy',1,3),fill('exit','exit','sell',6,4)],orders:[{id:'add',product_id:1},{id:'exit',product_id:1}],windowStart:2000,windowEnd:5000,historyComplete:true,mixedPosition:false});assert.equal(result.complete,false);});
test('Delta reporting start_time conversion is milliseconds to microseconds',()=>{assert.equal(toDeltaMicroseconds(1234),1234000);});
test('Delta reporting pagination is bounded and exposes incomplete coverage',async()=>{const complete=await boundedHistory(async(after)=>after?{result:[2],meta:{after:null}}:{result:[1],meta:{after:'next'}},10);assert.deepEqual(complete,{result:[1,2],complete:true});const limited=await boundedHistory(async()=>({result:[1],meta:{after:'next'}}),1);assert.deepEqual(limited,{result:[1],complete:false});});
test('simulated restart finds a proven stale OPEN close boundary before later activity',()=>{const boundary=findBotCloseBoundary({productId:1,entryOrderId:'entry',fills:[fill('e','entry','buy',5,2),fill('x','exit','sell',5,3),fill('later','manual','buy',2,4)]});assert.equal(boundary,3000);});
test('coverage requires every trade and remains additive across scopes',()=>{const bot=Array.from({length:10},(_,i)=>{const t=row('bot',i+1,i<8?1:null,null);if(i===0)t.netPnL=t.grossPnL!-1;return t;});const manual=Array.from({length:5},(_,i)=>row('exchange_existing',i+1,1,null));const botStats=calculateStats(bot),manualStats=calculateStats(manual),account=calculateStats([...bot,...manual]);assert.equal(botStats.brokerageReportedTrades,8);assert.equal(manualStats.brokerageReportedTrades,5);assert.equal(account.brokerageReportedTrades,13);assert.equal(botStats.gstReportedTrades,0);assert.equal(manualStats.gstReportedTrades,0);assert.equal(account.gstReportedTrades,0);assert.equal(botStats.fullyReconciledTrades,1);assert.equal(botStats.netPnLComplete,false);assert.equal(manualStats.netPnLComplete,false);assert.equal(account.netPnLComplete,false);assert.equal(account.totalTrades,15);assert.equal(account.brokerage,botStats.brokerage+manualStats.brokerage);});
test('zero-trade coverage is explicit and not a failure',()=>{const stats=calculateStats([]);assert.equal(stats.totalTrades,0);assert.equal(stats.netPnLComplete,false);assert.equal(stats.winRate,0);});
test('20 of 100 brokerage and 1 of 100 net records are explicitly incomplete',()=>{const rows=Array.from({length:100},(_,i)=>{const trade=row('bot',1,i<20?0.1:null,null);if(i===0)trade.netPnL=0.9;return trade;});const stats=calculateStats(rows);assert.equal(stats.brokerageReportedTrades,20);assert.equal(stats.brokerageComplete,false);assert.equal(stats.fullyReconciledTrades,1);assert.equal(stats.netPnLComplete,false);});
test('real persistence logic keeps bot OPEN and CLOSED reconciliation in one idempotent record',async()=>{const records=new Map<string,any>();const fills=[fill('e','entry','buy',5,2),fill('x1','exit1','sell',2,3),fill('x2','exit2','sell',3,4)];const orders=[botOrder,{id:'exit1',product_id:1,reduce_only:true},{id:'exit2',product_id:1,stop_order_type:'take_profit_order'}];const dependencies:TradePersistenceDependencies={upsert:(async(doc:any)=>{records.set(doc.tradeId,{...records.get(doc.tradeId),...doc});return records.get(doc.tradeId);}) as any,fills:(async()=>({result:fills,complete:true})) as any,orders:(async()=>({result:orders,complete:true})) as any,now:()=>5000};const active={direction:'long',source:'bot' as const,attributionStatus:'BOT_CONFIRMED',entryPrice:100,trigger:100,sl:90,tp:110,contracts:5,ownedContracts:5,contractValue:1,orderId:'entry',clientOrderId:'ema-123',openedAt:1000,riskAmount:50,mixedPosition:false};await persistOpenBotTrade(active,1,'XAUTUSD',dependencies);assert.equal(records.size,1);assert.equal([...records.values()][0].status,'OPEN');const first=await persistClosedTrade(active,1,'XAUTUSD',110,dependencies);const second=await persistClosedTrade(active,1,'XAUTUSD',110,dependencies);assert.equal(records.size,1);assert.equal(first.tradeId,second.tradeId);assert.equal([...records.values()][0].status,'CLOSED');assert.deepEqual(first.exitFillIds,['x1','x2']);});

const staleTrade={direction:'long',source:'bot' as const,attributionStatus:'BOT_CONFIRMED',entryPrice:100,trigger:100,sl:90,tp:110,contracts:5,ownedContracts:5,contractValue:1,orderId:'entry',clientOrderId:'ema-123',openedAt:1000,riskAmount:50,mixedPosition:false,closedAtBoundary:5000};
function stalePersistenceHarness(fills:any[],orders:any[],complete=true){let record:any={status:'RECONCILING',reconciliationError:'pending'};const dependencies:TradePersistenceDependencies={upsert:(async(doc:any)=>{record={...record,...doc};return record;}) as any,fills:(async()=>({result:fills,complete})) as any,orders:(async()=>({result:orders,complete})) as any,now:()=>5000};return {persist:()=>persistClosedTrade(staleTrade,1,'XAUTUSD',null,dependencies),record:()=>record};}
const liveTrade={...staleTrade,closedAtBoundary:undefined};
function livePersistenceHarness(fills:any[],orders:any[],complete=true){let record:any={status:'OPEN',reconciliationError:null};const dependencies:TradePersistenceDependencies={upsert:(async(doc:any)=>{record={...record,...doc};return record;}) as any,fills:(async()=>({result:fills,complete})) as any,orders:(async()=>({result:orders,complete})) as any,now:()=>5000};return {persist:()=>persistClosedTrade(liveTrade,1,'XAUTUSD',null,dependencies),record:()=>record};}
test('exact attributable live close becomes closed',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','exit','sell',5,3)];const harness=livePersistenceHarness(fills,[botOrder,{id:'exit',product_id:1,reduce_only:true}]);await harness.persist();assert.equal(harness.record().status,'CLOSED');});
test('live close with incomplete Delta pagination remains open for retry',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','exit','sell',5,3)];const harness=livePersistenceHarness(fills,[botOrder,{id:'exit',product_id:1,reduce_only:true}],false);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'OPEN');});
test('live close with missing exit order evidence remains open for retry',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','missing-exit','sell',5,3)];const harness=livePersistenceHarness(fills,[botOrder]);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'OPEN');});
test('live close with incomplete exit quantity remains open for retry',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','exit','sell',3,3)];const harness=livePersistenceHarness(fills,[botOrder,{id:'exit',product_id:1,reduce_only:true}]);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'OPEN');});
test('mixed bot and manual live lifecycle remains open for retry',async()=>{const fills=[fill('e','entry','buy',5,2),fill('m','manual','buy',2,3),fill('x','exit','sell',7,4)];const harness=livePersistenceHarness(fills,[botOrder,{id:'manual',product_id:1,client_order_id:'user-order'},{id:'exit',product_id:1,reduce_only:true}]);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'OPEN');});
test('later stale reconciliation closes an unresolved live record once evidence is complete',async()=>{let record:any={status:'OPEN',reconciliationError:null};let complete=false;const fills=[fill('e','entry','buy',5,2),fill('x','exit','sell',5,3)];const orders=[botOrder,{id:'exit',product_id:1,reduce_only:true}];const dependencies:TradePersistenceDependencies={upsert:(async(doc:any)=>{record={...record,...doc};return record;}) as any,fills:(async()=>({result:fills,complete})) as any,orders:(async()=>({result:orders,complete})) as any,now:()=>5000};await assert.rejects(()=>persistClosedTrade(liveTrade,1,'XAUTUSD',null,dependencies),/RECONCILIATION_INCOMPLETE/);assert.equal(record.status,'OPEN');complete=true;await persistClosedTrade(staleTrade,1,'XAUTUSD',null,dependencies);assert.equal(record.status,'CLOSED');});
test('exact single bot exit allows stale reconciliation to close',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','exit','sell',5,3)];assert.equal(findBotCloseBoundary({productId:1,entryOrderId:'entry',fills}),3000);const harness=stalePersistenceHarness(fills,[botOrder,{id:'exit',product_id:1,reduce_only:true}]);await harness.persist();assert.equal(harness.record().status,'CLOSED');});
test('mixed bot and manual stale lifecycle remains reconciling',async()=>{const fills=[fill('e','entry','buy',5,2),fill('m','manual','buy',2,3),fill('x','exit','sell',7,4)];assert.equal(findBotCloseBoundary({productId:1,entryOrderId:'entry',fills}),4000);const harness=stalePersistenceHarness(fills,[botOrder,{id:'manual',product_id:1,client_order_id:'user-order'},{id:'exit',product_id:1,reduce_only:true}]);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'RECONCILING');});
test('oversized stale exit remains reconciling',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','exit','sell',7,3)];assert.equal(findBotCloseBoundary({productId:1,entryOrderId:'entry',fills}),null);const harness=stalePersistenceHarness(fills,[botOrder,{id:'exit',product_id:1,reduce_only:true}]);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'RECONCILING');});
test('stale close with missing exit order evidence remains reconciling',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','missing-exit','sell',5,3)];const harness=stalePersistenceHarness(fills,[botOrder]);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'RECONCILING');});
test('stale close with incomplete Delta pagination remains reconciling',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x','exit','sell',5,3)];const harness=stalePersistenceHarness(fills,[botOrder,{id:'exit',product_id:1,reduce_only:true}],false);await assert.rejects(harness.persist,/RECONCILIATION_INCOMPLETE/);assert.equal(harness.record().status,'RECONCILING');});
test('exact multiple bot exit fills allow stale reconciliation to close',async()=>{const fills=[fill('e','entry','buy',5,2),fill('x1','exit-1','sell',2,3),fill('x2','exit-2','sell',3,4)];assert.equal(findBotCloseBoundary({productId:1,entryOrderId:'entry',fills}),4000);const harness=stalePersistenceHarness(fills,[botOrder,{id:'exit-1',product_id:1,reduce_only:true},{id:'exit-2',product_id:1,reduce_only:true}]);await harness.persist();assert.equal(harness.record().status,'CLOSED');});

const classifyExit=(side:'LONG'|'SHORT',exitOrder:any,exitPrice?:number)=>{const entrySide=side==='LONG'?'buy':'sell',exitSide=side==='LONG'?'sell':'buy';const entry={...fill('entry-fill','entry',entrySide,5,2),price:side==='LONG'?100:110};const exit={...fill('exit-fill','exit',exitSide,5,3),price:exitPrice??(side==='LONG'?110:100)};return classifyBotExitEvidence({side,productId:1,ownedContracts:5,entryOrderId:'entry',fills:[entry,exit],orders:[{...botOrder,side:entrySide},{id:'exit',product_id:1,...exitOrder}],windowStart:1000,windowEnd:4000,historyComplete:true,mixedPosition:false});};
test('LONG TP fill remains a win when ticker later moves below TP',()=>{const tickerAfterClose=90;const result=classifyExit('LONG',{stop_order_type:'take_profit_order'});assert.ok(tickerAfterClose<110);assert.equal(result.outcome,'WIN');assert.equal(applyDailyLossOutcome(3,result.outcome),0);});
test('SHORT TP fill remains a win when ticker later moves above TP',()=>{const tickerAfterClose=120;const result=classifyExit('SHORT',{stop_order_type:'take_profit_order'});assert.ok(tickerAfterClose>100);assert.equal(result.outcome,'WIN');assert.equal(applyDailyLossOutcome(2,result.outcome),0);});
test('profitable bot manual close before TP resets rather than increments consecutive losses',()=>{const result=classifyExit('LONG',{reduce_only:true},105);assert.equal(result.exitReason,'MANUAL_CLOSE');assert.equal(result.outcome,'WIN');assert.equal(applyDailyLossOutcome(4,result.outcome),0);});
test('losing bot manual close counts a realized loss without being labelled SL',()=>{const result=classifyExit('LONG',{reduce_only:true},95);assert.equal(result.exitReason,'MANUAL_CLOSE');assert.equal(result.outcome,'LOSS');assert.equal(applyDailyLossOutcome(4,result.outcome),5);});
test('proven SL increments and proven TP resets exactly once at close transition',()=>{const sl=classifyExit('LONG',{stop_order_type:'stop_loss_order'},90),tp=classifyExit('LONG',{stop_order_type:'take_profit_order'},110);assert.equal(sl.exitReason,'SL');assert.equal(applyDailyLossOutcome(2,sl.outcome),3);assert.equal(tp.exitReason,'TP');assert.equal(applyDailyLossOutcome(2,tp.outcome),0);});
test('unknown exit and MongoDB availability cannot fabricate a confirmed loss',()=>{const result=classifyBotExitEvidence({side:'LONG',productId:1,ownedContracts:5,entryOrderId:'entry',fills:[],orders:[],windowStart:1000,windowEnd:4000,historyComplete:false,mixedPosition:false});const mongoAvailable=false;assert.equal(mongoAvailable,false);assert.equal(result.outcome,'UNKNOWN');assert.equal(applyDailyLossOutcome(6,result.outcome),6);});

const deltaEpochMs=1725865012000;
const microFill=(fillId:string,orderId:string,side:'buy'|'sell',size:number,offsetMs:number)=>({id:fillId,order_id:orderId,product_id:1,side,size,price:side==='buy'?100:110,created_at:String((deltaEpochMs+offsetMs)*1000)});
test('Delta timestamp normalization supports microsecond strings and numbers',()=>{assert.equal(deltaTimestampMilliseconds('1725865012000000'),1725865012000);assert.equal(deltaTimestampMilliseconds(1725865012000000),1725865012000);});
test('Delta timestamp normalization supports milliseconds and ISO timestamps',()=>{assert.equal(deltaTimestampMilliseconds('1725865012000'),1725865012000);assert.equal(deltaTimestampMilliseconds(1725865012000),1725865012000);assert.equal(deltaTimestampMilliseconds('2026-08-30T12:00:00.000Z'),Date.parse('2026-08-30T12:00:00.000Z'));});
test('Delta timestamp normalization safely rejects invalid values',()=>{for(const value of [null,undefined,'','not-a-timestamp','1234'])assert.equal(deltaTimestampMilliseconds(value),null);});
test('bot TP and SL classification accepts Delta microsecond timestamps',()=>{const classify=(stop_order_type:string)=>classifyBotExitEvidence({side:'LONG',productId:1,ownedContracts:5,entryOrderId:'entry',fills:[microFill('entry-fill','entry','buy',5,0),microFill('exit-fill','exit','sell',5,1000)],orders:[{id:'entry',product_id:1,client_order_id:'ema-123'},{id:'exit',product_id:1,stop_order_type}],windowStart:deltaEpochMs-1000,windowEnd:deltaEpochMs+2000,historyComplete:true,mixedPosition:false});const tp=classify('take_profit_order'),sl=classify('stop_loss_order');assert.equal(tp.outcome,'WIN');assert.equal(tp.exitReason,'TP');assert.equal(sl.outcome,'LOSS');assert.equal(sl.exitReason,'SL');});
test('bot ownership can be confirmed with Delta microsecond timestamps',()=>{const result=resolvePositionOwnership({lookupFailed:false,currentSize:5,productId:1,persisted:{entryOrderId:'entry',entryClientOrderId:'ema-123',entryTime:new Date(deltaEpochMs),side:'LONG',contracts:5},fills:[microFill('entry-fill','entry','buy',5,0)],orders:[{id:'entry',product_id:1,client_order_id:'ema-123'}],historyComplete:true});assert.equal(result.status,'BOT_CONFIRMED');});
test('bot close boundary normalizes Delta microseconds to milliseconds',()=>{const boundary=findBotCloseBoundary({productId:1,entryOrderId:'entry',fills:[microFill('entry-fill','entry','buy',5,0),microFill('exit-fill','exit','sell',5,1000)]});assert.equal(boundary,deltaEpochMs+1000);});

test('manual LONG and SHORT use actual fills, commission, and proven SL evidence',async()=>{for(const direction of ['long','short'] as const){const records=new Map<string,any>(),entrySide=direction==='long'?'buy':'sell',exitSide=direction==='long'?'sell':'buy';const entry={...fill('manual-entry','manual-order',entrySide,2,2,'0.12'),price:100};const exit={...fill('manual-exit','sl-order',exitSide,2,3,'0.08'),price:direction==='long'?90:110};const dependencies:TradePersistenceDependencies={upsert:(async(doc:any)=>{records.set(doc.tradeId,{...records.get(doc.tradeId),...doc});return records.get(doc.tradeId);}) as any,fills:(async()=>({result:[entry,exit],complete:true})) as any,orders:(async()=>({result:[{id:'manual-order',product_id:1,client_order_id:'user-order'},{id:'sl-order',product_id:1,stop_order_type:'stop_loss_order'}],complete:true})) as any,now:()=>5000};const active:any={direction,source:'exchange_existing',attributionStatus:'MANUAL_CONFIRMED',contracts:2,ownedContracts:2,contractValue:1,openedAt:2000,mixedPosition:false};const opened=await persistOpenManualTrade(active,1,'XAUTUSD',[entry],dependencies),closed=await persistClosedTrade({...active,...opened},1,'XAUTUSD',null,dependencies);assert.equal(records.size,1);assert.equal(closed.exitReason,'SL');assert.equal(closed.grossPnL,-20);assert.ok(Math.abs((closed.brokerage??0)-0.2)<1e-12);assert.equal(closed.GST,null);assert.equal(closed.netPnL,null);}});
test('manual TP and profitable close use Delta order evidence',async()=>{for(const [stopType,expected] of [['take_profit_order','TP'],[undefined,'MANUAL_CLOSE']] as const){let record:any={};const entry={...fill('manual-entry','manual-order','buy',2,2),price:100},exit={...fill(`manual-exit-${expected}`,'exit-order','sell',2,3),price:110};const dependencies:TradePersistenceDependencies={upsert:(async(doc:any)=>record={...record,...doc}) as any,fills:(async()=>({result:[entry,exit],complete:true})) as any,orders:(async()=>({result:[{id:'manual-order',product_id:1,client_order_id:'user-order'},{id:'exit-order',product_id:1,stop_order_type:stopType}],complete:true})) as any,now:()=>5000};const active:any={direction:'long',source:'exchange_existing',attributionStatus:'MANUAL_CONFIRMED',contracts:2,ownedContracts:2,contractValue:1,openedAt:2000,mixedPosition:false};const opened=await persistOpenManualTrade(active,1,'XAUTUSD',[entry],dependencies),closed=await persistClosedTrade({...active,...opened},1,'XAUTUSD',null,dependencies);assert.equal(closed.exitReason,expected);assert.equal(closed.grossPnL,20);}});
test('manual incomplete evidence retries and later closes without duplication',async()=>{const records=new Map<string,any>(),entry=fill('manual-entry','manual-order','buy',2,2),exit=fill('manual-exit','exit-order','sell',2,3);let complete=false;const dependencies:TradePersistenceDependencies={upsert:(async(doc:any)=>{records.set(doc.tradeId,{...records.get(doc.tradeId),...doc});return records.get(doc.tradeId);}) as any,fills:(async()=>({result:[entry,exit],complete})) as any,orders:(async()=>({result:[{id:'manual-order',product_id:1,client_order_id:'user-order'},{id:'exit-order',product_id:1,stop_order_type:'stop_loss_order'}],complete})) as any,now:()=>5000};const active:any={direction:'long',source:'exchange_existing',attributionStatus:'MANUAL_CONFIRMED',contracts:2,ownedContracts:2,contractValue:1,openedAt:2000,mixedPosition:false};const opened=await persistOpenManualTrade(active,1,'XAUTUSD',[entry],dependencies);await assert.rejects(()=>persistClosedTrade({...active,...opened},1,'XAUTUSD',null,dependencies),/RECONCILIATION_INCOMPLETE/);assert.equal([...records.values()][0].status,'OPEN');complete=true;await persistClosedTrade({...active,...opened,closedAtBoundary:3000},1,'XAUTUSD',null,dependencies);await persistClosedTrade({...active,...opened,closedAtBoundary:3000},1,'XAUTUSD',null,dependencies);assert.equal(records.size,1);assert.equal([...records.values()][0].status,'CLOSED');});
test('persisted manual entry IDs recover a close boundary after partial close and restart',()=>{const fills=[fill('e1','entry','buy',3,2),fill('e2','entry','buy',2,3),fill('partial','partial-exit','sell',2,4),fill('final','final-exit','sell',3,5)];assert.equal(findTradeCloseBoundary({productId:1,entryFillIds:['e1','e2'],fills}),5000);});
test('attribution retry can change UNKNOWN to MANUAL or BOT only when evidence completes',()=>{const incomplete=resolvePositionOwnership({lookupFailed:false,currentSize:2,productId:1,persisted:null,fills:[fill('m','manual','buy',2,4)],orders:[],historyComplete:false});assert.equal(incomplete.status,'UNKNOWN');const manual=resolvePositionOwnership({lookupFailed:false,currentSize:2,productId:1,persisted:null,fills:[fill('m','manual','buy',2,4)],orders:[{id:'manual',product_id:1,client_order_id:'user-order'}],historyComplete:true});assert.equal(manual.status,'MANUAL_CONFIRMED');const bot=resolvePositionOwnership({lookupFailed:false,currentSize:2,productId:1,persisted:{entryOrderId:'bot-order',entryClientOrderId:'ema-retry',entryTime:new Date(1000),side:'LONG',contracts:2},fills:[fill('b','bot-order','buy',2,4)],orders:[{id:'bot-order',product_id:1,client_order_id:'ema-retry'}],historyComplete:true});assert.equal(bot.status,'BOT_CONFIRMED');});
