'use client';
import { FormEvent,useEffect,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import { claimPortfolioDeletion,releasePortfolioDeletion,removeDeletedPortfolio,requestPortfolioDeletion } from './portfolio-delete-client';
import { isPortfolioDeleteDisabled } from './portfolio-delete-eligibility';
type Environment='real'|'demo';
type Portfolio={id:string;symbol:string;productId:number;name:string|null;contractValue:number|null;settlingAsset:string|null;underlyingAsset:string|null;environment:Environment;currentPrice:number|null;deletion?:{allowed:boolean;positionKnown:boolean;positionSize:number|string|null;reason:string|null}};
export default function PortfolioManager(){
  const router=useRouter();
  const[rows,setRows]=useState<Portfolio[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[symbol,setSymbol]=useState(''),[environment,setEnvironment]=useState<Environment>('real'),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(''),[csrf,setCsrf]=useState('');const input=useRef<HTMLInputElement>(null),mounted=useRef(true),deletingRef=useRef('');
  async function load(initial=false){if(initial)setLoading(true);try{const response=await fetch('/api/portfolio',{cache:'no-store'});if(response.status===401){window.location.replace('/login');return;}const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load portfolio.');if(mounted.current)setRows(data.portfolio||[]);}catch(cause){if(initial&&mounted.current)setError(cause instanceof Error?cause.message:'Unable to load portfolio.');}finally{if(initial&&mounted.current)setLoading(false);}}
  useEffect(()=>{mounted.current=true;void load(true);fetch('/api/auth/session',{cache:'no-store'}).then(async response=>{if(response.ok&&mounted.current)setCsrf((await response.json()).csrfToken||'');});const refresh=window.setInterval(()=>{if(document.visibilityState==='visible')void load();},5000);return()=>{mounted.current=false;window.clearInterval(refresh);};},[]);
  useEffect(()=>{if(open)setTimeout(()=>input.current?.focus(),0);const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)setOpen(false);};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[open,busy]);
  useEffect(()=>{const navigate=(event:MouseEvent)=>{const target=event.target as HTMLElement;if(target.closest('button'))return;const card=target.closest('article.portfolioCard');if(!card)return;const cardSymbol=card.querySelector('h2')?.textContent,cardEnvironment=[...card.querySelectorAll('dl div')].find(item=>item.querySelector('dt')?.textContent==='Environment')?.querySelector('dd')?.textContent?.toLowerCase();const row=rows.find(item=>item.symbol===cardSymbol&&item.environment===cardEnvironment);if(row)router.push(`/futures/${row.environment==='real'?'live':'demo'}/${row.id}`);};document.addEventListener('click',navigate);return()=>document.removeEventListener('click',navigate);},[rows,router]);
  function showModal(){setError('');setSuccess('');setOpen(true);}function close(){if(!busy){setOpen(false);setSymbol('');setEnvironment('real');setError('');}}
  async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/portfolio',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({symbol,environment})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to save portfolio.');setRows(current=>[...current,data.portfolio]);setSuccess(`${data.portfolio.symbol} (${data.portfolio.environment.toUpperCase()}) added to Portfolio.`);setOpen(false);setSymbol('');setEnvironment('real');void load();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save portfolio.');}finally{setBusy(false);}}
  async function remove(row:Portfolio){if(!csrf||!window.confirm(`Delete ${row.symbol} (${row.environment.toUpperCase()}) from Portfolio?`)||!claimPortfolioDeletion(deletingRef,row.id))return;setDeleting(row.id);setError('');setSuccess('');try{await requestPortfolioDeletion(row.id,csrf);setRows(current=>removeDeletedPortfolio(current,row.id));setSuccess(`${row.symbol} (${row.environment.toUpperCase()}) deleted.`);}catch(cause){setError(cause instanceof Error?cause.message:'Unable to delete portfolio.');}finally{releasePortfolioDeletion(deletingRef);setDeleting('');}}
  return <><div className="portfolioActions"><button type="button" onClick={showModal}>+ ADD PORTFOLIO</button>{success&&<p className="successNotice" role="status">{success}</p>}{!open&&error&&<p className="settingsError" role="alert">{error}</p>}</div>{loading?<div className="portfolioGrid" aria-label="Loading portfolios">{[1,2,3].map(value=><div className="portfolioCard skeleton" key={value}/>)}</div>:rows.length?<div className="portfolioGrid">{rows.map(row=>{const deleteDisabled=isPortfolioDeleteDisabled(row.deletion,Boolean(deleting));return <article className="portfolioCard" key={row.id||`${row.environment}-${row.symbol}`}><div className="portfolioCardHead"><span className="portfolioType">FUTURES</span><button className="portfolioDelete" type="button" title={deleteDisabled?row.deletion?.reason||undefined:undefined} disabled={deleteDisabled||!csrf} onClick={()=>void remove(row)}>{deleting===row.id?'DELETING…':'DELETE'}</button></div>{deleteDisabled&&row.deletion?.reason&&<small className="portfolioDeleteReason">{row.deletion.reason}</small>}<h2>{row.symbol}</h2>{row.name&&<p>{row.name}</p>}<dl><div className="currentPrice"><dt>Current Price</dt><dd>{row.currentPrice==null?'Unavailable':row.currentPrice.toLocaleString(undefined,{maximumFractionDigits:12})}</dd></div><div><dt>Product ID</dt><dd>{row.productId}</dd></div>{row.contractValue!=null&&<div><dt>Contract Value</dt><dd>{row.contractValue}</dd></div>}<div><dt>Environment</dt><dd>{row.environment.toUpperCase()}</dd></div>{row.settlingAsset&&<div><dt>Settling Asset</dt><dd>{row.settlingAsset}</dd></div>}{row.underlyingAsset&&<div><dt>Underlying Asset</dt><dd>{row.underlyingAsset}</dd></div>}</dl></article>;})}</div>:<section className="portfolioEmpty"><span aria-hidden="true">▦</span><h2>No portfolios yet.</h2><p>Add your first Delta Exchange instrument to begin configuring your trading workspace.</p><button type="button" onClick={showModal}>+ Add Portfolio</button></section>}
  {open&&<div className="modalBackdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close();}}><section className="portfolioModal" role="dialog" aria-modal="true" aria-labelledby="add-portfolio-title"><button className="modalClose" type="button" aria-label="Close" onClick={close}>×</button><span className="eyebrow">DELTA EXCHANGE INSTRUMENT</span><h2 id="add-portfolio-title">Add Portfolio</h2><form onSubmit={submit}><label htmlFor="portfolio-symbol">Delta Exchange Symbol</label><input ref={input} id="portfolio-symbol" value={symbol} placeholder="BTCUSD" maxLength={30} disabled={busy} onChange={event=>setSymbol(event.target.value.trimStart().toUpperCase())}/><small>Examples: BTCUSD, XAUTUSD</small><fieldset className="environmentPicker"><legend>Trading Environment</legend>{(['real','demo'] as const).map(value=><label key={value} className={environment===value?'selected':''}><input type="radio" name="environment" value={value} checked={environment===value} disabled={busy} onChange={()=>setEnvironment(value)}/><span>{value.toUpperCase()}</span></label>)}</fieldset>{error&&<p className="settingsError" role="alert">{error}</p>}<div className="modalButtons"><button className="secondary" type="button" onClick={close} disabled={busy}>Cancel</button><button type="submit" disabled={busy||!csrf}>{busy?'VERIFYING…':'ADD PORTFOLIO'}</button></div></form></section></div>}</>;
}
