import { getAppMode } from '../../../lib/app-mode';
import { NextRequest,NextResponse } from 'next/server';
import { requireApiSession } from '../../../lib/auth/api';
import { listPortfolio } from '../../../lib/portfolio/repository';
import { createPortfolio,portfolioWithPrices,sanitizePortfolio } from '../../../lib/portfolio/service';
export const dynamic='force-dynamic';
const errors:Record<string,{message:string;status:number}>={SYMBOL_REQUIRED:{message:'Please enter a Delta Exchange symbol.',status:400},SYMBOL_FORMAT:{message:'Invalid symbol format.',status:400},SYMBOL_NOT_FOUND:{message:'This symbol is not available in the application mode.',status:400},PORTFOLIO_EXISTS:{message:'Portfolio already exists.',status:409},DELTA_VERIFICATION_FAILED:{message:'Unable to verify the symbol with Delta Exchange. Please try again.',status:502},PORTFOLIO_SAVE_FAILED:{message:'Unable to save portfolio.',status:500}};
export async function GET(req:NextRequest){const auth=await requireApiSession(req);if(!auth.ok)return auth.error;try{return NextResponse.json({appMode:getAppMode(),portfolio:await portfolioWithPrices(await listPortfolio())});}catch{return NextResponse.json({error:'Unable to load portfolio.'},{status:500});}}
export async function POST(req:NextRequest){const auth=await requireApiSession(req,{csrf:true});if(!auth.ok)return auth.error;let body:any;try{body=await req.json();}catch{return NextResponse.json({error:'Invalid JSON.'},{status:400});}if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(key=>!['symbol'].includes(key)))return NextResponse.json({error:'Request must contain only symbol.'},{status:400});try{return NextResponse.json({portfolio:{...sanitizePortfolio(await createPortfolio(body.symbol,undefined)),currentPrice:null}},{status:201});}catch(error:any){const safe=errors[String(error?.message)]??errors.PORTFOLIO_SAVE_FAILED;return NextResponse.json({error:safe.message},{status:safe.status});}}
export async function DELETE(_req:NextRequest){return NextResponse.json({error:'Portfolio deletion is not allowed.'},{status:405,headers:{Allow:'GET, POST'}});}
