import { NextRequest,NextResponse } from 'next/server';
import { requireApiSession } from '../../../lib/auth/api';
import { deletePortfolio,findPortfolioById,listPortfolio } from '../../../lib/portfolio/repository';
import { createPortfolio,portfolioWithPrices,sanitizePortfolio } from '../../../lib/portfolio/service';
import { deletePortfolioCoordinated } from '../../../lib/portfolio/deletion';
export const dynamic='force-dynamic';
const errors:Record<string,{message:string;status:number}>={SYMBOL_REQUIRED:{message:'Please enter a Delta Exchange symbol.',status:400},SYMBOL_FORMAT:{message:'Invalid symbol format.',status:400},ENVIRONMENT_REQUIRED:{message:'Please select a trading environment.',status:400},SYMBOL_NOT_FOUND:{message:'This symbol is not available in the selected Delta environment.',status:400},PORTFOLIO_EXISTS:{message:'Portfolio already exists.',status:409},DELTA_VERIFICATION_FAILED:{message:'Unable to verify the symbol with Delta Exchange. Please try again.',status:502},PORTFOLIO_SAVE_FAILED:{message:'Unable to save portfolio.',status:500}};
export async function GET(req:NextRequest){const auth=await requireApiSession(req);if(!auth.ok)return auth.error;try{return NextResponse.json({portfolio:await portfolioWithPrices(await listPortfolio())});}catch{return NextResponse.json({error:'Unable to load portfolio.'},{status:500});}}
export async function POST(req:NextRequest){const auth=await requireApiSession(req,{csrf:true});if(!auth.ok)return auth.error;let body:any;try{body=await req.json();}catch{return NextResponse.json({error:'Invalid JSON.'},{status:400});}if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(key=>!['symbol','environment'].includes(key)))return NextResponse.json({error:'Request must contain only symbol and environment.'},{status:400});try{return NextResponse.json({portfolio:{...sanitizePortfolio(await createPortfolio(body.symbol,body.environment)),currentPrice:null}},{status:201});}catch(error:any){const safe=errors[String(error?.message)]??errors.PORTFOLIO_SAVE_FAILED;return NextResponse.json({error:safe.message},{status:safe.status});}}
export async function DELETE(req:NextRequest){const auth=await requireApiSession(req,{csrf:true});if(!auth.ok)return auth.error;let body:any;try{body=await req.json();}catch{return NextResponse.json({error:'Invalid JSON.'},{status:400});}if(!body||typeof body.id!=='string'||Object.keys(body).some(key=>key!=='id'))return NextResponse.json({error:'A valid portfolio id is required.'},{status:400});try{const portfolio=await findPortfolioById(body.id);if(!portfolio)return NextResponse.json({error:'Portfolio not found.'},{status:404});const result=await deletePortfolioCoordinated(portfolio as any,deletePortfolio);if(result.ok)return NextResponse.json({ok:true});if(result.reason==='NOT_FOUND')return NextResponse.json({error:'Portfolio not found.'},{status:404});if(result.reason==='ACTIVE')return NextResponse.json({error:'Close the active position before deleting this portfolio.'},{status:409});if(result.reason==='ENTRY_UNRESOLVED')return NextResponse.json({error:'Portfolio deletion blocked while an entry is unresolved.'},{status:409});if(result.reason==='IN_PROGRESS')return NextResponse.json({error:'Portfolio entry or deletion is already in progress.'},{status:409});return NextResponse.json({error:'Unable to verify trading activity. Portfolio was not deleted.'},{status:502});}catch{return NextResponse.json({error:'Unable to verify trading activity. Portfolio was not deleted.'},{status:502});}}
